// Generated by sprotodump. DO NOT EDIT!
// source: C2S.sproto

namespace C2SSproto { 
	export class accu_rechar_item extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public recharge_money: number = 0;
		public rewards: Array<prop> = [];
		public summary: string = "";
		public note2: string = "";
		public note3: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.recharge_money = 0;
			this.rewards.length = 0;
			this.summary = "";
			this.note2 = "";
			this.note3 = "";
			return this;
		}

	}


	export class accu_rechar_stage extends Sp.SprotoTypeBase {
	
		public stage_info: act_stage_comm = new act_stage_comm();
		public accu_rechar_items: Array<accu_rechar_item> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.stage_info = <act_stage_comm>this.stage_info.reset();
			this.accu_rechar_items.length = 0;
			return this;
		}

	}


	export class act_stage_comm extends Sp.SprotoTypeBase {
	
		public stage: number = 0;
		public pic: string = "";
		public name: string = "";
		public start_time: number = 0;
		public end_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.stage = 0;
			this.pic = "";
			this.name = "";
			this.start_time = 0;
			this.end_time = 0;
			return this;
		}

	}


	export class activity_tab extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public name: string = "";
		public tag: number = 0;
		public readever: number = 0;
		public style: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.name = "";
			this.tag = 0;
			this.readever = 0;
			this.style = 0;
			return this;
		}

	}


	export class bind_phone_number_request extends Sp.SprotoTypeBase {
	
		public phone_number: string = "";
		public code: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.phone_number = "";
			this.code = "";
			return this;
		}

	}


	export class bind_phone_number_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			return this;
		}

	}


	export class bomb_fish_click_request extends Sp.SprotoTypeBase {
	
		public tag_id: number = 0;
		public status: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.tag_id = 0;
			this.status = 0;
			return this;
		}

	}


	export class cond extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public quantity: number = 0;
		public para: Array<number> = [];
		public para_range: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.quantity = 0;
			this.para.length = 0;
			this.para_range = 0;
			return this;
		}

	}


	export class daily_share extends Sp.SprotoTypeBase {
	
		public share_num: number = 0;
		public rewards: Array<prop> = [];
		public summary: string = "";
		public interval: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.share_num = 0;
			this.rewards.length = 0;
			this.summary = "";
			this.interval = 0;
			return this;
		}

	}


	export class delete_mail_request extends Sp.SprotoTypeBase {
	
		public guid: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.guid = "";
			return this;
		}

	}


	export class delete_mail_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public guid: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.guid = "";
			return this;
		}

	}


	export class eat_fish_request extends Sp.SprotoTypeBase {
	
		public eat_id: number = 0;
		public tag_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.eat_id = 0;
			this.tag_id = 0;
			return this;
		}

	}


	export class equipment extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public create_time: number = 0;
		public expire_time: number = 0;
		public is_use: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.create_time = 0;
			this.expire_time = 0;
			this.is_use = 0;
			return this;
		}

	}


	export class exchange_rcd extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public name: string = "";
		public consume_item: Array<prop> = [];
		public exchange_item: Array<prop> = [];
		public exchange_count: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.name = "";
			this.consume_item.length = 0;
			this.exchange_item.length = 0;
			this.exchange_count = 0;
			return this;
		}

	}


	export class fire_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public rot: string = "";
		public bullet_id: number = 0;
		public lock_fish_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.rot = "";
			this.bullet_id = 0;
			this.lock_fish_id = 0;
			return this;
		}

	}


	export class fish_net_request extends Sp.SprotoTypeBase {
	
		public net_type: number = 0;
		public factor: number = 0;
		public fishes: Array<victim> = [];
		public count: number = 0;
		public func_id: number = 0;
		public net_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.net_type = 0;
			this.factor = 0;
			this.fishes.length = 0;
			this.count = 0;
			this.func_id = 0;
			this.net_id = 0;
			return this;
		}

	}


	export class fish_net_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public uid: string = "";
		public fishes: Array<victim> = [];
		public factor: number = 0;
		public silo_award: number = 0;
		public total_gold: string = "";
		public add_gold: number = 0;
		public machine_storm: machine_storm = new machine_storm();
		public func_id: number = 0;
		public net_id: number = 0;
		public total_exp: number = 0;
		public invalid_tags: Array<number> = [];
		public total_diamond: number = 0;
		public gold_red_packet: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.uid = "";
			this.fishes.length = 0;
			this.factor = 0;
			this.silo_award = 0;
			this.total_gold = "";
			this.add_gold = 0;
			this.machine_storm = <machine_storm>this.machine_storm.reset();
			this.func_id = 0;
			this.net_id = 0;
			this.total_exp = 0;
			this.invalid_tags.length = 0;
			this.total_diamond = 0;
			this.gold_red_packet = 0;
			return this;
		}

	}


	export class forge_battery extends Sp.SprotoTypeBase {
	
		public multi_index: number = 0;
		public own_base_items: Array<prop> = [];
		public own_extra_items: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.multi_index = 0;
			this.own_base_items.length = 0;
			this.own_extra_items.length = 0;
			return this;
		}

	}


	export class func_penetration_shoot_request extends Sp.SprotoTypeBase {
	
		public net_id: number = 0;
		public rot: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.net_id = 0;
			this.rot = "";
			return this;
		}

	}


	export class func_penetration_shoot_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			return this;
		}

	}


	export class function_timer_start_request extends Sp.SprotoTypeBase {
	
		public func_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.func_id = 0;
			return this;
		}

	}


	export class function_timer_start_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public func_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.func_id = 0;
			return this;
		}

	}


	export class get_request extends Sp.SprotoTypeBase {
	
		public what: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.what = "";
			return this;
		}

	}


	export class get_response extends Sp.SprotoTypeBase {
	
		public result: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.result = "";
			return this;
		}

	}


	export class get_fast_login_account_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class get_fast_login_account_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public openid: string = "";
		public token: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.openid = "";
			this.token = "";
			return this;
		}

	}


	export class get_mail_list_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class get_mail_list_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			return this;
		}

	}


	export class get_newbie_guide_progress_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class get_newbie_guide_progress_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public progress: Array<newbie_guide_step> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.progress.length = 0;
			return this;
		}

	}


	export class get_redpoint_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class get_redpoint_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public redpoint: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.redpoint.length = 0;
			return this;
		}

	}


	export class get_user_bio_request extends Sp.SprotoTypeBase {
	
		public account_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.account_id = 0;
			return this;
		}

	}


	export class get_user_bio_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public user_bio: user_bio = new user_bio();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.user_bio = <user_bio>this.user_bio.reset();
			return this;
		}

	}


	export class get_user_equipment_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class get_user_equipment_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public data: Array<equipment> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.data.length = 0;
			return this;
		}

	}


	export class give_prop_2_others_request extends Sp.SprotoTypeBase {
	
		public account_id: number = 0;
		public id: number = 0;
		public quantity: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.account_id = 0;
			this.id = 0;
			this.quantity = 0;
			return this;
		}

	}


	export class give_prop_2_others_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public id: number = 0;
		public quantity: number = 0;
		public total_remain_give_cnt: number = 0;
		public hunshi_remain_give_cnt: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.id = 0;
			this.quantity = 0;
			this.total_remain_give_cnt = 0;
			this.hunshi_remain_give_cnt = 0;
			return this;
		}

	}


	export class given_items extends Sp.SprotoTypeBase {
	
		public prop_items: Array<prop> = [];
		public equip_list_active: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.prop_items.length = 0;
			this.equip_list_active.length = 0;
			return this;
		}

	}


	export class gm_request extends Sp.SprotoTypeBase {
	
		public cmd: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.cmd = "";
			return this;
		}

	}


	export class gm_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public help: string = "";
		public result: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.help = "";
			this.result = "";
			return this;
		}

	}


	export class grow_up_task_info extends Sp.SprotoTypeBase {
	
		public task_id: number = 0;
		public completed_num: number = 0;
		public status: number = 0;
		public day_seq: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.task_id = 0;
			this.completed_num = 0;
			this.status = 0;
			this.day_seq = 0;
			return this;
		}

	}


	export class handshake_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class heartbeat_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class heartbeat_response extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class inv_info extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public name: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.name = "";
			return this;
		}

	}


	export class invite_bind extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public inv_rewards: Array<prop> = [];
		public inved_rewards: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.inv_rewards.length = 0;
			this.inved_rewards.length = 0;
			return this;
		}

	}


	export class invite_task extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public simple: string = "";
		public simple1: string = "";
		public complete_condition: cond = new cond();
		public rewards: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.simple = "";
			this.simple1 = "";
			this.complete_condition = <cond>this.complete_condition.reset();
			this.rewards.length = 0;
			return this;
		}

	}


	export class item_exchange extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public name: string = "";
		public consume_lottery: number = 0;
		public remain_quantity: number = 0;
		public recommended: number = 0;
		public tips_icon: number = 0;
		public icon: string = "";
		public consume_type: number = 0;
		public reward_type: number = 0;
		public item_list: Array<prop> = [];
		public item_desc: string = "";
		public ex_day_in_week: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.name = "";
			this.consume_lottery = 0;
			this.remain_quantity = 0;
			this.recommended = 0;
			this.tips_icon = 0;
			this.icon = "";
			this.consume_type = 0;
			this.reward_type = 0;
			this.item_list.length = 0;
			this.item_desc = "";
			this.ex_day_in_week.length = 0;
			return this;
		}

	}


	export class item_reward_lucky_purch extends Sp.SprotoTypeBase {
	
		public stage: number = 0;
		public name: number = 0;
		public acc_name: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.stage = 0;
			this.name = 0;
			this.acc_name = "";
			return this;
		}

	}


	export class liveness_info extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public value: number = 0;
		public rewarded_record: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.value = 0;
			this.rewarded_record.length = 0;
			return this;
		}

	}


	export class login_request extends Sp.SprotoTypeBase {
	
		public account_type: string = "";
		public openid: string = "";
		public token: string = "";
		public device_info: string = "";
		public appver: string = "";
		public extra: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.account_type = "";
			this.openid = "";
			this.token = "";
			this.device_info = "";
			this.appver = "";
			this.extra = "";
			return this;
		}

	}


	export class login_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public user_info: string = "";
		public openid: string = "";
		public token: string = "";
		public app_update_info: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.user_info = "";
			this.openid = "";
			this.token = "";
			this.app_update_info = "";
			return this;
		}

	}


	export class lucky_purch extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public purched_num: number = 0;
		public draw_time: number = 0;
		public my_purched_num: number = 0;
		public status: number = 0;
		public stage: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.purched_num = 0;
			this.draw_time = 0;
			this.my_purched_num = 0;
			this.status = 0;
			this.stage = 0;
			return this;
		}

	}


	export class lucky_purch_item extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public stage: number = 0;
		public name: string = "";
		public rewards: Array<prop> = [];
		public req_qty: number = 0;
		public consume_type: number = 0;
		public valid_time: number = 0;
		public show_tab: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.stage = 0;
			this.name = "";
			this.rewards.length = 0;
			this.req_qty = 0;
			this.consume_type = 0;
			this.valid_time = 0;
			this.show_tab = 0;
			return this;
		}

	}


	export class machine_storm extends Sp.SprotoTypeBase {
	
		public init: boolean = false;
		public silo_id: number = 0;
		public time: number = 0;
		public factor: number = 0;
		public add_time: number = 0;
		public add_factor: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.init = false;
			this.silo_id = 0;
			this.time = 0;
			this.factor = 0;
			this.add_time = 0;
			this.add_factor = 0;
			return this;
		}

	}


	export class modify_nickname_request extends Sp.SprotoTypeBase {
	
		public cost_type: number = 0;
		public new_nickname: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.cost_type = 0;
			this.new_nickname = "";
			return this;
		}

	}


	export class modify_nickname_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public total_diamond: number = 0;
		public cost_diamond: number = 0;
		public cost_prop: prop = new prop();
		public new_nickname: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.total_diamond = 0;
			this.cost_diamond = 0;
			this.cost_prop = <prop>this.cost_prop.reset();
			this.new_nickname = "";
			return this;
		}

	}


	export class new_fish_item extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public simple: string = "";
		public simple1: string = "";
		public complete_condition: cond = new cond();
		public rewards: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.simple = "";
			this.simple1 = "";
			this.complete_condition = <cond>this.complete_condition.reset();
			this.rewards.length = 0;
			return this;
		}

	}


	export class new_fish_stage extends Sp.SprotoTypeBase {
	
		public stage_info: act_stage_comm = new act_stage_comm();
		public new_fish_items: Array<new_fish_item> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.stage_info = <act_stage_comm>this.stage_info.reset();
			this.new_fish_items.length = 0;
			return this;
		}

	}


	export class new_task_info extends Sp.SprotoTypeBase {
	
		public task_id: number = 0;
		public completed_num: number = 0;
		public status: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.task_id = 0;
			this.completed_num = 0;
			this.status = 0;
			return this;
		}

	}


	export class newbie_guide_step extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public count: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.count = 0;
			return this;
		}

	}


	export class ninja_card extends Sp.SprotoTypeBase {
	
		public index: number = 0;
		public type: number = 0;
		public extra: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.index = 0;
			this.type = 0;
			this.extra = 0;
			return this;
		}

	}


	export class open_mail_request extends Sp.SprotoTypeBase {
	
		public guid: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.guid = "";
			return this;
		}

	}


	export class open_mail_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public guid: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.guid = "";
			return this;
		}

	}


	export class package1 extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public session: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.session = 0;
			return this;
		}

	}


	export class prop extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public quantity: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.quantity = 0;
			return this;
		}

	}


	export class purch_item extends Sp.SprotoTypeBase {
	
		public acc_id: number = 0;
		public stage: number = 0;
		public id: number = 0;
		public purched_num: number = 0;
		public status: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.acc_id = 0;
			this.stage = 0;
			this.id = 0;
			this.purched_num = 0;
			this.status = 0;
			return this;
		}

	}


	export class quick_sign_up_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class quick_sign_up_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public players: Array<table_player> = [];
		public chair_id: number = 0;
		public room_id: number = 0;
		public frozen_end_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.players.length = 0;
			this.chair_id = 0;
			this.room_id = 0;
			this.frozen_end_time = 0;
			return this;
		}

	}


	export class rank_config extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public kill_fish: number = 0;
		public targets: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.kill_fish = 0;
			this.targets.length = 0;
			return this;
		}

	}


	export class reach_cond extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public num: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.num = 0;
			return this;
		}

	}


	export class recd_exchanged extends Sp.SprotoTypeBase {
	
		public name: string = "";
		public lottery: number = 0;
		public icon: string = "";
		public time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.name = "";
			this.lottery = 0;
			this.icon = "";
			this.time = 0;
			return this;
		}

	}


	export class recycle_prop_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public quantity: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.quantity = 0;
			return this;
		}

	}


	export class recycle_prop_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public reward: Array<prop> = [];
		public total_gold: string = "";
		public id: number = 0;
		public quantity: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.reward.length = 0;
			this.total_gold = "";
			this.id = 0;
			this.quantity = 0;
			return this;
		}

	}


	export class req_activity_cfg_request extends Sp.SprotoTypeBase {
	
		public ac_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.ac_id = 0;
			return this;
		}

	}


	export class req_activity_cfg_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public ac_id: number = 0;
		public daily_share_cfg: Array<daily_share> = [];
		public invite_task_cfg: Array<invite_task> = [];
		public invite_bind_cfg: Array<invite_bind> = [];
		public exchange_item_cfg: Array<exchange_rcd> = [];
		public new_fish_expert_cfg: new_fish_stage = new new_fish_stage();
		public lucky_purch_cfg: Array<lucky_purch_item> = [];
		public accu_recharge_cfg: accu_rechar_stage = new accu_rechar_stage();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.ac_id = 0;
			this.daily_share_cfg.length = 0;
			this.invite_task_cfg.length = 0;
			this.invite_bind_cfg.length = 0;
			this.exchange_item_cfg.length = 0;
			this.new_fish_expert_cfg = <new_fish_stage>this.new_fish_expert_cfg.reset();
			this.lucky_purch_cfg.length = 0;
			this.accu_recharge_cfg = <accu_rechar_stage>this.accu_recharge_cfg.reset();
			return this;
		}

	}


	export class req_activity_reward_request extends Sp.SprotoTypeBase {
	
		public ac_id: number = 0;
		public tid: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.ac_id = 0;
			this.tid = 0;
			return this;
		}

	}


	export class req_activity_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public ac_id: number = 0;
		public tid: number = 0;
		public rewarded: given_items = new given_items();
		public total_diamond: number = 0;
		public total_gold: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.ac_id = 0;
			this.tid = 0;
			this.rewarded = <given_items>this.rewarded.reset();
			this.total_diamond = 0;
			this.total_gold = 0;
			return this;
		}

	}


	export class req_activity_tab_list_request extends Sp.SprotoTypeBase {
	
		public style: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.style = 0;
			return this;
		}

	}


	export class req_activity_tab_list_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public activities: Array<activity_tab> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.activities.length = 0;
			return this;
		}

	}


	export class req_backpack_data_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public props: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.props.length = 0;
			return this;
		}

	}


	export class req_battery_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_battery_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public show_forge_battery: forge_battery = new forge_battery();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.show_forge_battery = <forge_battery>this.show_forge_battery.reset();
			return this;
		}

	}


	export class req_buy_gos_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			return this;
		}

	}


	export class req_buy_gos_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public extra: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.extra = "";
			return this;
		}

	}


	export class req_buy_monthly_card_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_buy_monthly_card_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public order_number: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.order_number = "";
			return this;
		}

	}


	export class req_cannon_reward_request extends Sp.SprotoTypeBase {
	
		public days: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.days = 0;
			return this;
		}

	}


	export class req_cannon_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public days: number = 0;
		public given_cannon: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.days = 0;
			this.given_cannon = 0;
			return this;
		}

	}


	export class req_catch_fish_expert_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_catch_fish_expert_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public number: number = 0;
		public rewarded: Array<number> = [];
		public start_time: number = 0;
		public end_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.number = 0;
			this.rewarded.length = 0;
			this.start_time = 0;
			this.end_time = 0;
			return this;
		}

	}


	export class req_cd_key_reward_request extends Sp.SprotoTypeBase {
	
		public key_code: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.key_code = "";
			return this;
		}

	}


	export class req_cd_key_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public rewarded: given_items = new given_items();
		public total_diamond: number = 0;
		public total_gold: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.rewarded = <given_items>this.rewarded.reset();
			this.total_diamond = 0;
			this.total_gold = "";
			return this;
		}

	}


	export class req_change_cannon_multiple_request extends Sp.SprotoTypeBase {
	
		public multiple: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.multiple = 0;
			return this;
		}

	}


	export class req_change_cannon_multiple_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public multiple: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.multiple = 0;
			return this;
		}

	}


	export class req_click_mall_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_click_mall_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public vip_show_vip_exchange: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.vip_show_vip_exchange = 0;
			return this;
		}

	}


	export class req_click_pop_interface_request extends Sp.SprotoTypeBase {
	
		public activity_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.activity_id = 0;
			return this;
		}

	}


	export class req_com_daily_share_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_com_daily_share_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public rewarded: number = 0;
		public rewarded_num: number = 0;
		public next_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.rewarded = 0;
			this.rewarded_num = 0;
			this.next_time = 0;
			return this;
		}

	}


	export class req_common_activity_info_request extends Sp.SprotoTypeBase {
	
		public activity_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.activity_id = 0;
			return this;
		}

	}


	export class req_common_activity_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public activity_id: number = 0;
		public quantity: number = 0;
		public rewarded: Array<number> = [];
		public start_time: number = 0;
		public end_time: number = 0;
		public circle_time: number = 0;
		public start_daily: number = 0;
		public end_daily: number = 0;
		public curr_stage: number = 0;
		public next_reward_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.activity_id = 0;
			this.quantity = 0;
			this.rewarded.length = 0;
			this.start_time = 0;
			this.end_time = 0;
			this.circle_time = 0;
			this.start_daily = 0;
			this.end_daily = 0;
			this.curr_stage = 0;
			this.next_reward_time = 0;
			return this;
		}

	}


	export class req_common_activity_reward_request extends Sp.SprotoTypeBase {
	
		public activity_id: number = 0;
		public index: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.activity_id = 0;
			this.index = 0;
			return this;
		}

	}


	export class req_common_activity_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public activity_id: number = 0;
		public index: number = 0;
		public given_items: Array<prop> = [];
		public given_equip_active: Array<number> = [];
		public total_diamond: number = 0;
		public total_gold: string = "";
		public rewarded_all: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.activity_id = 0;
			this.index = 0;
			this.given_items.length = 0;
			this.given_equip_active.length = 0;
			this.total_diamond = 0;
			this.total_gold = "";
			this.rewarded_all = 0;
			return this;
		}

	}


	export class req_do_lottery_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_do_lottery_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public lucky_item: prop = new prop();
		public multiple: number = 0;
		public pos_index: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.lucky_item = <prop>this.lucky_item.reset();
			this.multiple = 0;
			this.pos_index = 0;
			return this;
		}

	}


	export class req_do_lottery_gold_fish_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_do_lottery_gold_fish_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public type: number = 0;
		public reward_index: number = 0;
		public total_gold: string = "";
		public total_diamond: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.type = 0;
			this.reward_index = 0;
			this.total_gold = "";
			this.total_diamond = 0;
			return this;
		}

	}


	export class req_do_new_sign_in_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_do_new_sign_in_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public multiple: sign_in_multiple = new sign_in_multiple();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.multiple = <sign_in_multiple>this.multiple.reset();
			return this;
		}

	}


	export class req_do_select_sand_task_request extends Sp.SprotoTypeBase {
	
		public select_task_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.select_task_id = 0;
			return this;
		}

	}


	export class req_do_select_sand_task_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public select_task_id: number = 0;
		public day_seq: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.select_task_id = 0;
			this.day_seq = 0;
			return this;
		}

	}


	export class req_energy_factor_unlock_request extends Sp.SprotoTypeBase {
	
		public use_extra_item: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.use_extra_item = 0;
			return this;
		}

	}


	export class req_energy_factor_unlock_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public unlock_index: number = 0;
		public energy_factor: number = 0;
		public props: Array<prop> = [];
		public total_diamond: number = 0;
		public total_gold: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.unlock_index = 0;
			this.energy_factor = 0;
			this.props.length = 0;
			this.total_diamond = 0;
			this.total_gold = "";
			return this;
		}

	}


	export class req_energy_rank_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_energy_rank_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public score: string = "";
		public user_rank: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.score = "";
			this.user_rank = 0;
			return this;
		}

	}


	export class req_exchange_mall_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			return this;
		}

	}


	export class req_exchange_mall_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public get_real_item: number = 0;
		public given_items: Array<prop> = [];
		public total_gold: string = "";
		public total_diamond: number = 0;
		public total_lottery: number = 0;
		public id: number = 0;
		public consume_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.get_real_item = 0;
			this.given_items.length = 0;
			this.total_gold = "";
			this.total_diamond = 0;
			this.total_lottery = 0;
			this.id = 0;
			this.consume_type = 0;
			return this;
		}

	}


	export class req_fish_expert_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_fish_expert_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public task_list: Array<new_task_info> = [];
		public start_time: number = 0;
		public end_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.task_list.length = 0;
			this.start_time = 0;
			this.end_time = 0;
			return this;
		}

	}


	export class req_fish_expert_reward_request extends Sp.SprotoTypeBase {
	
		public task_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.task_id = 0;
			return this;
		}

	}


	export class req_fish_expert_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public task_id: number = 0;
		public rewarded: given_items = new given_items();
		public total_diamond: number = 0;
		public total_gold: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.task_id = 0;
			this.rewarded = <given_items>this.rewarded.reset();
			this.total_diamond = 0;
			this.total_gold = 0;
			return this;
		}

	}


	export class req_gift_request extends Sp.SprotoTypeBase {
	
		public pos: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.pos = 0;
			return this;
		}

	}


	export class req_gift_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			return this;
		}

	}


	export class req_gold_fish_lottery_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_gold_fish_lottery_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public gold_fish_score: number = 0;
		public gold_fish_num: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.gold_fish_score = 0;
			this.gold_fish_num = 0;
			return this;
		}

	}


	export class req_grow_up_activity_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_grow_up_activity_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public create_time: number = 0;
		public total_score: number = 0;
		public task_list: Array<grow_up_task_info> = [];
		public score_rewarded: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.create_time = 0;
			this.total_score = 0;
			this.task_list.length = 0;
			this.score_rewarded.length = 0;
			return this;
		}

	}


	export class req_grow_up_task_reward_request extends Sp.SprotoTypeBase {
	
		public task_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.task_id = 0;
			return this;
		}

	}


	export class req_grow_up_task_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public task_id: number = 0;
		public rewarded: given_items = new given_items();
		public total_score: number = 0;
		public total_diamond: number = 0;
		public total_gold: string = "";
		public rewarded_all: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.task_id = 0;
			this.rewarded = <given_items>this.rewarded.reset();
			this.total_score = 0;
			this.total_diamond = 0;
			this.total_gold = "";
			this.rewarded_all = 0;
			return this;
		}

	}


	export class req_last_energy_rank_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_last_energy_rank_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public score: string = "";
		public user_rank: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.score = "";
			this.user_rank = 0;
			return this;
		}

	}


	export class req_last_rank_info_request extends Sp.SprotoTypeBase {
	
		public rank_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rank_type = 0;
			return this;
		}

	}


	export class req_last_rank_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public rank_type: number = 0;
		public score: string = "";
		public user_rank: number = 0;
		public turn: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.rank_type = 0;
			this.score = "";
			this.user_rank = 0;
			this.turn = 0;
			return this;
		}

	}


	export class req_liveness_reward_request extends Sp.SprotoTypeBase {
	
		public reward_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.reward_id = 0;
			return this;
		}

	}


	export class req_liveness_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public reward_id: number = 0;
		public reward_item: prop = new prop();
		public total_gold: string = "";
		public total_diamond: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.reward_id = 0;
			this.reward_item = <prop>this.reward_item.reset();
			this.total_gold = "";
			this.total_diamond = 0;
			return this;
		}

	}


	export class req_lock_fish_request extends Sp.SprotoTypeBase {
	
		public tag_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.tag_id = 0;
			return this;
		}

	}


	export class req_lock_fish_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			return this;
		}

	}


	export class req_lottery_list_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_lottery_list_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public gift_items: Array<prop> = [];
		public is_seventh_lottery: number = 0;
		public is_done_lottery_today: number = 0;
		public rewarded_record: Array<reward_info_day> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.gift_items.length = 0;
			this.is_seventh_lottery = 0;
			this.is_done_lottery_today = 0;
			this.rewarded_record.length = 0;
			return this;
		}

	}


	export class req_mall_exchange_info_request extends Sp.SprotoTypeBase {
	
		public show_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.show_type = 0;
			return this;
		}

	}


	export class req_mall_exchange_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public items: Array<item_exchange> = [];
		public show_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.items.length = 0;
			this.show_type = 0;
			return this;
		}

	}


	export class req_mall_info_request extends Sp.SprotoTypeBase {
	
		public mall_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.mall_type = 0;
			return this;
		}

	}


	export class req_mark_gift_request extends Sp.SprotoTypeBase {
	
		public gid: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.gid = 0;
			return this;
		}

	}


	export class req_mobile_package_request extends Sp.SprotoTypeBase {
	
		public channel_id: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.channel_id = "";
			return this;
		}

	}


	export class req_mobile_package_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public url: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.url = "";
			return this;
		}

	}


	export class req_monthly_card_ui_data_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_monthly_card_ui_data_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public end_time: number = 0;
		public today_received: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.end_time = 0;
			this.today_received = 0;
			return this;
		}

	}


	export class req_mul_activity_request extends Sp.SprotoTypeBase {
	
		public ac_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.ac_id = 0;
			return this;
		}

	}


	export class req_mul_activity_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public ac_id: number = 0;
		public task_list: Array<new_task_info> = [];
		public inviter: inv_info = new inv_info();
		public inved_count: number = 0;
		public start_time: number = 0;
		public end_time: number = 0;
		public lucky_purch_ui: Array<lucky_purch> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.ac_id = 0;
			this.task_list.length = 0;
			this.inviter = <inv_info>this.inviter.reset();
			this.inved_count = 0;
			this.start_time = 0;
			this.end_time = 0;
			this.lucky_purch_ui.length = 0;
			return this;
		}

	}


	export class req_my_lucky_purch_record_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_my_lucky_purch_record_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public purch_rcds: Array<purch_item> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.purch_rcds.length = 0;
			return this;
		}

	}


	export class req_need_pop_interface_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_need_pop_interface_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public activity_id_list: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.activity_id_list.length = 0;
			return this;
		}

	}


	export class req_new_sign_in_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_new_sign_in_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public multiples: Array<sign_in_multiple> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.multiples.length = 0;
			return this;
		}

	}


	export class req_ninja_round_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_ninja_round_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public round: number = 0;
		public timeout: number = 0;
		public cards: Array<ninja_card> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.round = 0;
			this.timeout = 0;
			this.cards.length = 0;
			return this;
		}

	}


	export class req_ninja_uncover_request extends Sp.SprotoTypeBase {
	
		public index: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.index = 0;
			return this;
		}

	}


	export class req_ninja_uncover_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public index: number = 0;
		public cards: Array<ninja_card> = [];
		public gold: number = 0;
		public total_gold: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.index = 0;
			this.cards.length = 0;
			this.gold = 0;
			this.total_gold = "";
			return this;
		}

	}


	export class req_open_backpack_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_payment_order_request extends Sp.SprotoTypeBase {
	
		public pay_sdk_type: number = 0;
		public out_trade_no: string = "";
		public pay_mode: number = 0;
		public extra: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.pay_sdk_type = 0;
			this.out_trade_no = "";
			this.pay_mode = 0;
			this.extra = "";
			return this;
		}

	}


	export class req_payment_order_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public order_info: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.order_info = "";
			return this;
		}

	}


	export class req_purch_lucky_purch_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public purch_num: number = 0;
		public stage: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.purch_num = 0;
			this.stage = 0;
			return this;
		}

	}


	export class req_purch_lucky_purch_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public id: number = 0;
		public remain_pur_num: number = 0;
		public my_purched_num: number = 0;
		public remain_item: prop = new prop();
		public stage: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.id = 0;
			this.remain_pur_num = 0;
			this.my_purched_num = 0;
			this.remain_item = <prop>this.remain_item.reset();
			this.stage = 0;
			return this;
		}

	}


	export class req_quick_task_reward_request extends Sp.SprotoTypeBase {
	
		public task_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.task_type = 0;
			return this;
		}

	}


	export class req_quick_task_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public task_type: number = 0;
		public task_ids: Array<number> = [];
		public total_gold: string = "";
		public total_diamond: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.task_type = 0;
			this.task_ids.length = 0;
			this.total_gold = "";
			this.total_diamond = 0;
			return this;
		}

	}


	export class req_rank_config_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_rank_config_response extends Sp.SprotoTypeBase {
	
		public config: Array<rank_config> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.config.length = 0;
			return this;
		}

	}


	export class req_rank_info_request extends Sp.SprotoTypeBase {
	
		public rank_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rank_type = 0;
			return this;
		}

	}


	export class req_rank_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public rank_type: number = 0;
		public score: string = "";
		public user_rank: number = 0;
		public turn: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.rank_type = 0;
			this.score = "";
			this.user_rank = 0;
			this.turn = 0;
			return this;
		}

	}


	export class req_receive_monthly_card_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_receive_monthly_card_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public reward_items: Array<prop> = [];
		public total_diamond: number = 0;
		public total_gold: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.reward_items.length = 0;
			this.total_diamond = 0;
			this.total_gold = "";
			return this;
		}

	}


	export class req_red_packet_exchange_request extends Sp.SprotoTypeBase {
	
		public exchange_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.exchange_id = 0;
			return this;
		}

	}


	export class req_red_packet_exchange_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public exchange_id: number = 0;
		public is_tel_fare: number = 0;
		public value: number = 0;
		public red_packet_value: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.exchange_id = 0;
			this.is_tel_fare = 0;
			this.value = 0;
			this.red_packet_value = 0;
			return this;
		}

	}


	export class req_red_packet_exchange_info_request extends Sp.SprotoTypeBase {
	
		public value: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.value = 0;
			return this;
		}

	}


	export class req_red_packet_exchange_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public value: number = 0;
		public items: Array<item_exchange> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.value = 0;
			this.items.length = 0;
			return this;
		}

	}


	export class req_red_packet_reward_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_red_packet_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public red_packet_value: number = 0;
		public random_index: number = 0;
		public cosumed_gold: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.red_packet_value = 0;
			this.random_index = 0;
			this.cosumed_gold = 0;
			return this;
		}

	}


	export class req_reward_catch_fish_expert_request extends Sp.SprotoTypeBase {
	
		public index: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.index = 0;
			return this;
		}

	}


	export class req_reward_catch_fish_expert_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public index: number = 0;
		public total_diamond: number = 0;
		public total_gold: string = "";
		public rewarded: given_items = new given_items();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.index = 0;
			this.total_diamond = 0;
			this.total_gold = "";
			this.rewarded = <given_items>this.rewarded.reset();
			return this;
		}

	}


	export class req_reward_record_lucky_purch_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_reward_record_lucky_purch_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public reward_rcds: Array<item_reward_lucky_purch> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.reward_rcds.length = 0;
			return this;
		}

	}


	export class req_room_act_rank_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_room_act_rank_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public score: string = "";
		public user_rank: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.score = "";
			this.user_rank = 0;
			return this;
		}

	}


	export class req_room_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_room_info_response extends Sp.SprotoTypeBase {
	
		public players: Array<table_player> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.players.length = 0;
			return this;
		}

	}


	export class req_room_list_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_room_list_response extends Sp.SprotoTypeBase {
	
		public list: Array<room_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.list.length = 0;
			return this;
		}

	}


	export class req_sand_task_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_sand_task_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public task_record: Array<sand_task_record> = [];
		public today_received: number = 0;
		public select_tasks: Array<number> = [];
		public cannon_reward: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.task_record.length = 0;
			this.today_received = 0;
			this.select_tasks.length = 0;
			this.cannon_reward.length = 0;
			return this;
		}

	}


	export class req_sand_task_reward_request extends Sp.SprotoTypeBase {
	
		public day_seq: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.day_seq = 0;
			return this;
		}

	}


	export class req_sand_task_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public day_seq: number = 0;
		public task_id: number = 0;
		public total_gold: string = "";
		public total_diamond: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.day_seq = 0;
			this.task_id = 0;
			this.total_gold = "";
			this.total_diamond = 0;
			return this;
		}

	}


	export class req_server_time_request extends Sp.SprotoTypeBase {
	
		public client_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.client_time = 0;
			return this;
		}

	}


	export class req_server_time_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public client_time: number = 0;
		public server_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.client_time = 0;
			this.server_time = 0;
			return this;
		}

	}


	export class req_take_gift_request extends Sp.SprotoTypeBase {
	
		public gid: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.gid = 0;
			return this;
		}

	}


	export class req_take_gift_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public gid: number = 0;
		public pos: number = 0;
		public extra: string = "";
		public total_gold: string = "";
		public total_diamond: number = 0;
		public items: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.gid = 0;
			this.pos = 0;
			this.extra = "";
			this.total_gold = "";
			this.total_diamond = 0;
			this.items.length = 0;
			return this;
		}

	}


	export class req_task_list_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_task_list_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public task_list: Array<task_info> = [];
		public liveness: Array<liveness_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.task_list.length = 0;
			this.liveness.length = 0;
			return this;
		}

	}


	export class req_task_reward_request extends Sp.SprotoTypeBase {
	
		public task_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.task_id = 0;
			return this;
		}

	}


	export class req_task_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public task_id: number = 0;
		public total_gold: string = "";
		public total_diamond: number = 0;
		public next_main: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.task_id = 0;
			this.total_gold = "";
			this.total_diamond = 0;
			this.next_main = 0;
			return this;
		}

	}


	export class req_today_give_prop_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_today_give_prop_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public total_remain_give_cnt: number = 0;
		public hunshi_remain_give_cnt: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.total_remain_give_cnt = 0;
			this.hunshi_remain_give_cnt = 0;
			return this;
		}

	}


	export class req_upgrade_battery_request extends Sp.SprotoTypeBase {
	
		public use_extra_item: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.use_extra_item = 0;
			return this;
		}

	}


	export class req_upgrade_battery_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public unlock_multi_index: number = 0;
		public show_forge_battery: forge_battery = new forge_battery();
		public total_diamond: number = 0;
		public total_gold: string = "";
		public use_extra_item: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.unlock_multi_index = 0;
			this.show_forge_battery = <forge_battery>this.show_forge_battery.reset();
			this.total_diamond = 0;
			this.total_gold = "";
			this.use_extra_item = 0;
			return this;
		}

	}


	export class req_user_exchanged_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class req_user_exchanged_info_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public recd_list: Array<recd_exchanged> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.recd_list.length = 0;
			return this;
		}

	}


	export class req_vdaily_reward_request extends Sp.SprotoTypeBase {
	
		public method: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.method = "";
			return this;
		}

	}


	export class req_vdaily_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public method: string = "";
		public total_gold: string = "";
		public total_diamond: number = 0;
		public rewards: Array<prop> = [];
		public next_gold: number = 0;
		public vip: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.method = "";
			this.total_gold = "";
			this.total_diamond = 0;
			this.rewards.length = 0;
			this.next_gold = 0;
			this.vip = 0;
			return this;
		}

	}


	export class req_write_inviter_request extends Sp.SprotoTypeBase {
	
		public inv_acc_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.inv_acc_id = 0;
			return this;
		}

	}


	export class req_write_inviter_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			return this;
		}

	}


	export class request_bankrupt_request extends Sp.SprotoTypeBase {
	
		public is_take: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.is_take = 0;
			return this;
		}

	}


	export class request_bankrupt_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public break_times: number = 0;
		public timeout: number = 0;
		public gold_amount: number = 0;
		public total_gold: string = "";
		public left_times: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.break_times = 0;
			this.timeout = 0;
			this.gold_amount = 0;
			this.total_gold = "";
			this.left_times = 0;
			return this;
		}

	}


	export class request_purchase_request extends Sp.SprotoTypeBase {
	
		public mall_id: number = 0;
		public goods_id: number = 0;
		public count: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.mall_id = 0;
			this.goods_id = 0;
			this.count = 0;
			return this;
		}

	}


	export class request_purchase_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public items: Array<prop> = [];
		public total_gold: string = "";
		public total_diamond: number = 0;
		public mall_id: number = 0;
		public goods_id: number = 0;
		public count: number = 0;
		public extra: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.items.length = 0;
			this.total_gold = "";
			this.total_diamond = 0;
			this.mall_id = 0;
			this.goods_id = 0;
			this.count = 0;
			this.extra = "";
			return this;
		}

	}


	export class request_update_rookie_request extends Sp.SprotoTypeBase {
	
		public value: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.value = 0;
			return this;
		}

	}


	export class reward_info_day extends Sp.SprotoTypeBase {
	
		public day_seq: number = 0;
		public item: prop = new prop();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.day_seq = 0;
			this.item = <prop>this.item.reset();
			return this;
		}

	}


	export class room_energy_exchange_request extends Sp.SprotoTypeBase {
	
		public itemid: number = 0;
		public count: number = 0;
		public exchange_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.itemid = 0;
			this.count = 0;
			this.exchange_type = 0;
			return this;
		}

	}


	export class room_energy_exchange_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public energy: string = "";
		public itemid: number = 0;
		public count: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.energy = "";
			this.itemid = 0;
			this.count = 0;
			return this;
		}

	}


	export class room_info extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public name: string = "";
		public can_enter: boolean = false;
		public unlocked: boolean = false;
		public start_time: number = 0;
		public end_time: number = 0;
		public is_open: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.name = "";
			this.can_enter = false;
			this.unlocked = false;
			this.start_time = 0;
			this.end_time = 0;
			this.is_open = 0;
			return this;
		}

	}


	export class room_quit_request extends Sp.SprotoTypeBase {
	
		public mark: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.mark = 0;
			return this;
		}

	}


	export class room_quit_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public mark: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.mark = 0;
			return this;
		}

	}


	export class room_sign_up_request extends Sp.SprotoTypeBase {
	
		public room_id: number = 0;
		public table_id: number = 0;
		public ignore_table_id: number = 0;
		public table_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.room_id = 0;
			this.table_id = 0;
			this.ignore_table_id = 0;
			this.table_type = 0;
			return this;
		}

	}


	export class room_sign_up_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public players: Array<table_player> = [];
		public chair_id: number = 0;
		public room_id: number = 0;
		public frozen_end_time: number = 0;
		public table_id: number = 0;
		public table_status: number = 0;
		public table_type: number = 0;
		public room_slots_open: boolean = false;
		public slots_star: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.players.length = 0;
			this.chair_id = 0;
			this.room_id = 0;
			this.frozen_end_time = 0;
			this.table_id = 0;
			this.table_status = 0;
			this.table_type = 0;
			this.room_slots_open = false;
			this.slots_star = 0;
			return this;
		}

	}


	export class room_slots_luckydraw_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			return this;
		}

	}


	export class room_slots_luckydraw_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public award: Array<prop> = [];
		public star: number = 0;
		public award_id: number = 0;
		public small_game_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.award.length = 0;
			this.star = 0;
			this.award_id = 0;
			this.small_game_id = 0;
			return this;
		}

	}


	export class sand_task_record extends Sp.SprotoTypeBase {
	
		public select_task: task_info = new task_info();
		public unselect_task_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.select_task = <task_info>this.select_task.reset();
			this.unselect_task_id = 0;
			return this;
		}

	}


	export class send_sms_verification_code_request extends Sp.SprotoTypeBase {
	
		public phone_number: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.phone_number = "";
			return this;
		}

	}


	export class send_sms_verification_code_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			return this;
		}

	}


	export class set_activity_read_request extends Sp.SprotoTypeBase {
	
		public guid: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.guid = 0;
			return this;
		}

	}


	export class set_newbie_guide_step_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			return this;
		}

	}


	export class set_newbie_guide_step_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			return this;
		}

	}


	export class sign_in_multiple extends Sp.SprotoTypeBase {
	
		public day_seq: number = 0;
		public multiple: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.day_seq = 0;
			this.multiple = 0;
			return this;
		}

	}


	export class switch_equipment_request extends Sp.SprotoTypeBase {
	
		public from_id: number = 0;
		public to_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.from_id = 0;
			this.to_id = 0;
			return this;
		}

	}


	export class switch_equipment_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public from_id: number = 0;
		public to_id: number = 0;
		public equip: equipment = new equipment();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.from_id = 0;
			this.to_id = 0;
			this.equip = <equipment>this.equip.reset();
			return this;
		}

	}


	export class sync_machine_storm_gold_request extends Sp.SprotoTypeBase {
	
		public gold: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.gold = 0;
			return this;
		}

	}


	export class sync_user_info_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class sync_user_info_response extends Sp.SprotoTypeBase {
	
		public gold: string = "";
		public energy: string = "";
		public diamond: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.gold = "";
			this.energy = "";
			this.diamond = 0;
			return this;
		}

	}


	export class table_player extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public chair_id: number = 0;
		public gold: string = "";
		public level: number = 0;
		public gender: number = 0;
		public nickname: string = "";
		public img_url: string = "";
		public diamond: number = 0;
		public unlock_battery: number = 0;
		public using_cannon: number = 0;
		public using_skill_ids: Array<number> = [];
		public cannon_id_raise_weight: number = 0;
		public cannon_power: number = 0;
		public using_cannon_multiple: number = 0;
		public is_bankruptcy: boolean = false;
		public items: Array<prop> = [];
		public account_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.chair_id = 0;
			this.gold = "";
			this.level = 0;
			this.gender = 0;
			this.nickname = "";
			this.img_url = "";
			this.diamond = 0;
			this.unlock_battery = 0;
			this.using_cannon = 0;
			this.using_skill_ids.length = 0;
			this.cannon_id_raise_weight = 0;
			this.cannon_power = 0;
			this.using_cannon_multiple = 0;
			this.is_bankruptcy = false;
			this.items.length = 0;
			this.account_id = 0;
			return this;
		}

	}


	export class take_mail_reward_request extends Sp.SprotoTypeBase {
	
		public guid: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.guid = "";
			return this;
		}

	}


	export class take_mail_reward_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public guid: string = "";
		public reward: Array<prop> = [];
		public total_gold: string = "";
		public total_diamond: number = 0;
		public total_lottery: number = 0;
		public equip_list_active: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.guid = "";
			this.reward.length = 0;
			this.total_gold = "";
			this.total_diamond = 0;
			this.total_lottery = 0;
			this.equip_list_active.length = 0;
			return this;
		}

	}


	export class task_info extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public status: number = 0;
		public cond_list: Array<reach_cond> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.status = 0;
			this.cond_list.length = 0;
			return this;
		}

	}


	export class unbind_phone_number_request extends Sp.SprotoTypeBase {
	
		public phone_number: string = "";
		public code: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.phone_number = "";
			this.code = "";
			return this;
		}

	}


	export class unbind_phone_number_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			return this;
		}

	}


	export class update_user_bio_request extends Sp.SprotoTypeBase {
	
		public signature: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.signature = "";
			return this;
		}

	}


	export class update_user_bio_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			return this;
		}

	}


	export class use_prop_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public quantity: number = 0;
		public buy: number = 0;
		public test: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.quantity = 0;
			this.buy = 0;
			this.test = 0;
			return this;
		}

	}


	export class use_prop_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
		public props: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			this.props.length = 0;
			return this;
		}

	}


	export class use_spec_bullet_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public fishes: Array<victim> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.fishes.length = 0;
			return this;
		}

	}


	export class use_spec_bullet_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public id: number = 0;
		public quantity: number = 0;
		public gold: number = 0;
		public total_gold: string = "";
		public fishes: Array<victim> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.id = 0;
			this.quantity = 0;
			this.gold = 0;
			this.total_gold = "";
			this.fishes.length = 0;
			return this;
		}

	}


	export class user_bio extends Sp.SprotoTypeBase {
	
		public account_id: number = 0;
		public nickname: string = "";
		public img_url: string = "";
		public gender: number = 0;
		public gold: string = "";
		public diamond: number = 0;
		public level: number = 0;
		public vip: number = 0;
		public signature: string = "";
		public cannon_multiple: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.account_id = 0;
			this.nickname = "";
			this.img_url = "";
			this.gender = 0;
			this.gold = "";
			this.diamond = 0;
			this.level = 0;
			this.vip = 0;
			this.signature = "";
			this.cannon_multiple = 0;
			return this;
		}

	}


	export class user_feedback_request extends Sp.SprotoTypeBase {
	
		public contact: string = "";
		public type: number = 0;
		public detail: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.contact = "";
			this.type = 0;
			this.detail = "";
			return this;
		}

	}


	export class user_feedback_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			return this;
		}

	}


	export class verify_phone_number_request extends Sp.SprotoTypeBase {
	
		public phone_number: string = "";
		public code: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.phone_number = "";
			this.code = "";
			return this;
		}

	}


	export class verify_phone_number_response extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public error_msg: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.error_msg = "";
			return this;
		}

	}


	export class victim extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public tag_id: number = 0;
		public score: number = 0;
		public func_id: number = 0;
		public net_id: number = 0;
		public items: Array<prop> = [];
		public factor_list: Array<number> = [];
		public func_param: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.tag_id = 0;
			this.score = 0;
			this.func_id = 0;
			this.net_id = 0;
			this.items.length = 0;
			this.factor_list.length = 0;
			this.func_param = 0;
			return this;
		}

	}


}

