// Generated by sprotodump. DO NOT EDIT!
class C2SProtocol extends Sp.ProtocolBase {
	public readonly bind_phone_number: number = 190;
	public readonly bomb_fish_click: number = 148;
	public readonly delete_mail: number = 131;
	public readonly eat_fish: number = 133;
	public readonly fire: number = 112;
	public readonly fish_net: number = 113;
	public readonly func_penetration_shoot: number = 171;
	public readonly function_timer_start: number = 120;
	public readonly get: number = 2;
	public readonly get_fast_login_account: number = 149;
	public readonly get_mail_list: number = 127;
	public readonly get_newbie_guide_progress: number = 157;
	public readonly get_redpoint: number = 151;
	public readonly get_user_bio: number = 153;
	public readonly get_user_equipment: number = 122;
	public readonly give_prop_2_others: number = 126;
	public readonly gm: number = 109;
	public readonly handshake: number = 1;
	public readonly heartbeat: number = 3;
	public readonly login: number = 100;
	public readonly modify_nickname: number = 191;
	public readonly open_mail: number = 128;
	public readonly quick_sign_up: number = 136;
	public readonly recycle_prop: number = 108;
	public readonly req_activity_cfg: number = 201;
	public readonly req_activity_reward: number = 206;
	public readonly req_activity_tab_list: number = 168;
	public readonly req_backpack_data: number = 106;
	public readonly req_battery: number = 121;
	public readonly req_buy_gos: number = 213;
	public readonly req_buy_monthly_card: number = 164;
	public readonly req_cannon_reward: number = 141;
	public readonly req_catch_fish_expert_info: number = 165;
	public readonly req_cd_key_reward: number = 145;
	public readonly req_change_cannon_multiple: number = 130;
	public readonly req_click_mall_info: number = 199;
	public readonly req_click_pop_interface: number = 169;
	public readonly req_com_daily_share: number = 202;
	public readonly req_common_activity_info: number = 176;
	public readonly req_common_activity_reward: number = 177;
	public readonly req_do_lottery: number = 111;
	public readonly req_do_lottery_gold_fish: number = 125;
	public readonly req_do_new_sign_in: number = 115;
	public readonly req_do_select_sand_task: number = 139;
	public readonly req_energy_factor_unlock: number = 185;
	public readonly req_energy_rank_info: number = 197;
	public readonly req_exchange_mall: number = 155;
	public readonly req_fish_expert: number = 192;
	public readonly req_fish_expert_reward: number = 193;
	public readonly req_gift: number = 143;
	public readonly req_gold_fish_lottery: number = 124;
	public readonly req_grow_up_activity: number = 180;
	public readonly req_grow_up_task_reward: number = 181;
	public readonly req_last_energy_rank_info: number = 198;
	public readonly req_last_rank_info: number = 183;
	public readonly req_liveness_reward: number = 119;
	public readonly req_lock_fish: number = 132;
	public readonly req_lottery_list: number = 110;
	public readonly req_mall_exchange_info: number = 154;
	public readonly req_mall_info: number = 156;
	public readonly req_mark_gift: number = 173;
	public readonly req_mobile_package: number = 196;
	public readonly req_monthly_card_ui_data: number = 162;
	public readonly req_mul_activity: number = 205;
	public readonly req_my_lucky_purch_record: number = 212;
	public readonly req_need_pop_interface: number = 167;
	public readonly req_new_sign_in_info: number = 114;
	public readonly req_ninja_round: number = 178;
	public readonly req_ninja_uncover: number = 179;
	public readonly req_open_backpack: number = 175;
	public readonly req_payment_order: number = 161;
	public readonly req_purch_lucky_purch: number = 209;
	public readonly req_quick_task_reward: number = 117;
	public readonly req_rank_config: number = 187;
	public readonly req_rank_info: number = 160;
	public readonly req_receive_monthly_card: number = 163;
	public readonly req_red_packet_exchange: number = 189;
	public readonly req_red_packet_exchange_info: number = 188;
	public readonly req_red_packet_reward: number = 186;
	public readonly req_reward_catch_fish_expert: number = 166;
	public readonly req_reward_record_lucky_purch: number = 211;
	public readonly req_room_act_rank_info: number = 195;
	public readonly req_room_info: number = 172;
	public readonly req_room_list: number = 101;
	public readonly req_sand_task_info: number = 138;
	public readonly req_sand_task_reward: number = 140;
	public readonly req_server_time: number = 147;
	public readonly req_take_gift: number = 142;
	public readonly req_task_list: number = 104;
	public readonly req_task_reward: number = 105;
	public readonly req_today_give_prop_info: number = 174;
	public readonly req_upgrade_battery: number = 116;
	public readonly req_user_exchanged_info: number = 159;
	public readonly req_vdaily_reward: number = 170;
	public readonly req_write_inviter: number = 204;
	public readonly request_bankrupt: number = 146;
	public readonly request_purchase: number = 135;
	public readonly request_update_rookie: number = 144;
	public readonly room_energy_exchange: number = 184;
	public readonly room_quit: number = 103;
	public readonly room_sign_up: number = 102;
	public readonly room_slots_luckydraw: number = 210;
	public readonly send_sms_verification_code: number = 194;
	public readonly set_activity_read: number = 137;
	public readonly set_newbie_guide_step: number = 158;
	public readonly switch_equipment: number = 123;
	public readonly sync_machine_storm_gold: number = 150;
	public readonly sync_user_info: number = 208;
	public readonly take_mail_reward: number = 129;
	public readonly unbind_phone_number: number = 200;
	public readonly update_user_bio: number = 152;
	public readonly use_prop: number = 107;
	public readonly use_spec_bullet: number = 134;
	public readonly user_feedback: number = 203;
	public readonly verify_phone_number: number = 207;

	public constructor() {
		super()
	
		this.Protocol.SetProtocol(this.bind_phone_number);
		this.Protocol.SetRequest(this.bind_phone_number ,C2SSproto.bind_phone_number_request);
		this.Protocol.SetResponse(this.bind_phone_number ,C2SSproto.bind_phone_number_response);

		this.Protocol.SetProtocol(this.bomb_fish_click);
		this.Protocol.SetRequest(this.bomb_fish_click ,C2SSproto.bomb_fish_click_request);

		this.Protocol.SetProtocol(this.delete_mail);
		this.Protocol.SetRequest(this.delete_mail ,C2SSproto.delete_mail_request);
		this.Protocol.SetResponse(this.delete_mail ,C2SSproto.delete_mail_response);

		this.Protocol.SetProtocol(this.eat_fish);
		this.Protocol.SetRequest(this.eat_fish ,C2SSproto.eat_fish_request);

		this.Protocol.SetProtocol(this.fire);
		this.Protocol.SetRequest(this.fire ,C2SSproto.fire_request);

		this.Protocol.SetProtocol(this.fish_net);
		this.Protocol.SetRequest(this.fish_net ,C2SSproto.fish_net_request);
		this.Protocol.SetResponse(this.fish_net ,C2SSproto.fish_net_response);

		this.Protocol.SetProtocol(this.func_penetration_shoot);
		this.Protocol.SetRequest(this.func_penetration_shoot ,C2SSproto.func_penetration_shoot_request);
		this.Protocol.SetResponse(this.func_penetration_shoot ,C2SSproto.func_penetration_shoot_response);

		this.Protocol.SetProtocol(this.function_timer_start);
		this.Protocol.SetRequest(this.function_timer_start ,C2SSproto.function_timer_start_request);
		this.Protocol.SetResponse(this.function_timer_start ,C2SSproto.function_timer_start_response);

		this.Protocol.SetProtocol(this.get);
		this.Protocol.SetRequest(this.get ,C2SSproto.get_request);
		this.Protocol.SetResponse(this.get ,C2SSproto.get_response);

		this.Protocol.SetProtocol(this.get_fast_login_account);
		this.Protocol.SetRequest(this.get_fast_login_account ,C2SSproto.get_fast_login_account_request);
		this.Protocol.SetResponse(this.get_fast_login_account ,C2SSproto.get_fast_login_account_response);

		this.Protocol.SetProtocol(this.get_mail_list);
		this.Protocol.SetRequest(this.get_mail_list ,C2SSproto.get_mail_list_request);
		this.Protocol.SetResponse(this.get_mail_list ,C2SSproto.get_mail_list_response);

		this.Protocol.SetProtocol(this.get_newbie_guide_progress);
		this.Protocol.SetRequest(this.get_newbie_guide_progress ,C2SSproto.get_newbie_guide_progress_request);
		this.Protocol.SetResponse(this.get_newbie_guide_progress ,C2SSproto.get_newbie_guide_progress_response);

		this.Protocol.SetProtocol(this.get_redpoint);
		this.Protocol.SetRequest(this.get_redpoint ,C2SSproto.get_redpoint_request);
		this.Protocol.SetResponse(this.get_redpoint ,C2SSproto.get_redpoint_response);

		this.Protocol.SetProtocol(this.get_user_bio);
		this.Protocol.SetRequest(this.get_user_bio ,C2SSproto.get_user_bio_request);
		this.Protocol.SetResponse(this.get_user_bio ,C2SSproto.get_user_bio_response);

		this.Protocol.SetProtocol(this.get_user_equipment);
		this.Protocol.SetRequest(this.get_user_equipment ,C2SSproto.get_user_equipment_request);
		this.Protocol.SetResponse(this.get_user_equipment ,C2SSproto.get_user_equipment_response);

		this.Protocol.SetProtocol(this.give_prop_2_others);
		this.Protocol.SetRequest(this.give_prop_2_others ,C2SSproto.give_prop_2_others_request);
		this.Protocol.SetResponse(this.give_prop_2_others ,C2SSproto.give_prop_2_others_response);

		this.Protocol.SetProtocol(this.gm);
		this.Protocol.SetRequest(this.gm ,C2SSproto.gm_request);
		this.Protocol.SetResponse(this.gm ,C2SSproto.gm_response);

		this.Protocol.SetProtocol(this.handshake);
		this.Protocol.SetRequest(this.handshake ,C2SSproto.handshake_request);

		this.Protocol.SetProtocol(this.heartbeat);
		this.Protocol.SetRequest(this.heartbeat ,C2SSproto.heartbeat_request);
		this.Protocol.SetResponse(this.heartbeat ,C2SSproto.heartbeat_response);

		this.Protocol.SetProtocol(this.login);
		this.Protocol.SetRequest(this.login ,C2SSproto.login_request);
		this.Protocol.SetResponse(this.login ,C2SSproto.login_response);

		this.Protocol.SetProtocol(this.modify_nickname);
		this.Protocol.SetRequest(this.modify_nickname ,C2SSproto.modify_nickname_request);
		this.Protocol.SetResponse(this.modify_nickname ,C2SSproto.modify_nickname_response);

		this.Protocol.SetProtocol(this.open_mail);
		this.Protocol.SetRequest(this.open_mail ,C2SSproto.open_mail_request);
		this.Protocol.SetResponse(this.open_mail ,C2SSproto.open_mail_response);

		this.Protocol.SetProtocol(this.quick_sign_up);
		this.Protocol.SetRequest(this.quick_sign_up ,C2SSproto.quick_sign_up_request);
		this.Protocol.SetResponse(this.quick_sign_up ,C2SSproto.quick_sign_up_response);

		this.Protocol.SetProtocol(this.recycle_prop);
		this.Protocol.SetRequest(this.recycle_prop ,C2SSproto.recycle_prop_request);
		this.Protocol.SetResponse(this.recycle_prop ,C2SSproto.recycle_prop_response);

		this.Protocol.SetProtocol(this.req_activity_cfg);
		this.Protocol.SetRequest(this.req_activity_cfg ,C2SSproto.req_activity_cfg_request);
		this.Protocol.SetResponse(this.req_activity_cfg ,C2SSproto.req_activity_cfg_response);

		this.Protocol.SetProtocol(this.req_activity_reward);
		this.Protocol.SetRequest(this.req_activity_reward ,C2SSproto.req_activity_reward_request);
		this.Protocol.SetResponse(this.req_activity_reward ,C2SSproto.req_activity_reward_response);

		this.Protocol.SetProtocol(this.req_activity_tab_list);
		this.Protocol.SetRequest(this.req_activity_tab_list ,C2SSproto.req_activity_tab_list_request);
		this.Protocol.SetResponse(this.req_activity_tab_list ,C2SSproto.req_activity_tab_list_response);

		this.Protocol.SetProtocol(this.req_backpack_data);
		this.Protocol.SetResponse(this.req_backpack_data ,C2SSproto.req_backpack_data_response);

		this.Protocol.SetProtocol(this.req_battery);
		this.Protocol.SetRequest(this.req_battery ,C2SSproto.req_battery_request);
		this.Protocol.SetResponse(this.req_battery ,C2SSproto.req_battery_response);

		this.Protocol.SetProtocol(this.req_buy_gos);
		this.Protocol.SetRequest(this.req_buy_gos ,C2SSproto.req_buy_gos_request);
		this.Protocol.SetResponse(this.req_buy_gos ,C2SSproto.req_buy_gos_response);

		this.Protocol.SetProtocol(this.req_buy_monthly_card);
		this.Protocol.SetRequest(this.req_buy_monthly_card ,C2SSproto.req_buy_monthly_card_request);
		this.Protocol.SetResponse(this.req_buy_monthly_card ,C2SSproto.req_buy_monthly_card_response);

		this.Protocol.SetProtocol(this.req_cannon_reward);
		this.Protocol.SetRequest(this.req_cannon_reward ,C2SSproto.req_cannon_reward_request);
		this.Protocol.SetResponse(this.req_cannon_reward ,C2SSproto.req_cannon_reward_response);

		this.Protocol.SetProtocol(this.req_catch_fish_expert_info);
		this.Protocol.SetRequest(this.req_catch_fish_expert_info ,C2SSproto.req_catch_fish_expert_info_request);
		this.Protocol.SetResponse(this.req_catch_fish_expert_info ,C2SSproto.req_catch_fish_expert_info_response);

		this.Protocol.SetProtocol(this.req_cd_key_reward);
		this.Protocol.SetRequest(this.req_cd_key_reward ,C2SSproto.req_cd_key_reward_request);
		this.Protocol.SetResponse(this.req_cd_key_reward ,C2SSproto.req_cd_key_reward_response);

		this.Protocol.SetProtocol(this.req_change_cannon_multiple);
		this.Protocol.SetRequest(this.req_change_cannon_multiple ,C2SSproto.req_change_cannon_multiple_request);
		this.Protocol.SetResponse(this.req_change_cannon_multiple ,C2SSproto.req_change_cannon_multiple_response);

		this.Protocol.SetProtocol(this.req_click_mall_info);
		this.Protocol.SetRequest(this.req_click_mall_info ,C2SSproto.req_click_mall_info_request);
		this.Protocol.SetResponse(this.req_click_mall_info ,C2SSproto.req_click_mall_info_response);

		this.Protocol.SetProtocol(this.req_click_pop_interface);
		this.Protocol.SetRequest(this.req_click_pop_interface ,C2SSproto.req_click_pop_interface_request);

		this.Protocol.SetProtocol(this.req_com_daily_share);
		this.Protocol.SetRequest(this.req_com_daily_share ,C2SSproto.req_com_daily_share_request);
		this.Protocol.SetResponse(this.req_com_daily_share ,C2SSproto.req_com_daily_share_response);

		this.Protocol.SetProtocol(this.req_common_activity_info);
		this.Protocol.SetRequest(this.req_common_activity_info ,C2SSproto.req_common_activity_info_request);
		this.Protocol.SetResponse(this.req_common_activity_info ,C2SSproto.req_common_activity_info_response);

		this.Protocol.SetProtocol(this.req_common_activity_reward);
		this.Protocol.SetRequest(this.req_common_activity_reward ,C2SSproto.req_common_activity_reward_request);
		this.Protocol.SetResponse(this.req_common_activity_reward ,C2SSproto.req_common_activity_reward_response);

		this.Protocol.SetProtocol(this.req_do_lottery);
		this.Protocol.SetRequest(this.req_do_lottery ,C2SSproto.req_do_lottery_request);
		this.Protocol.SetResponse(this.req_do_lottery ,C2SSproto.req_do_lottery_response);

		this.Protocol.SetProtocol(this.req_do_lottery_gold_fish);
		this.Protocol.SetRequest(this.req_do_lottery_gold_fish ,C2SSproto.req_do_lottery_gold_fish_request);
		this.Protocol.SetResponse(this.req_do_lottery_gold_fish ,C2SSproto.req_do_lottery_gold_fish_response);

		this.Protocol.SetProtocol(this.req_do_new_sign_in);
		this.Protocol.SetRequest(this.req_do_new_sign_in ,C2SSproto.req_do_new_sign_in_request);
		this.Protocol.SetResponse(this.req_do_new_sign_in ,C2SSproto.req_do_new_sign_in_response);

		this.Protocol.SetProtocol(this.req_do_select_sand_task);
		this.Protocol.SetRequest(this.req_do_select_sand_task ,C2SSproto.req_do_select_sand_task_request);
		this.Protocol.SetResponse(this.req_do_select_sand_task ,C2SSproto.req_do_select_sand_task_response);

		this.Protocol.SetProtocol(this.req_energy_factor_unlock);
		this.Protocol.SetRequest(this.req_energy_factor_unlock ,C2SSproto.req_energy_factor_unlock_request);
		this.Protocol.SetResponse(this.req_energy_factor_unlock ,C2SSproto.req_energy_factor_unlock_response);

		this.Protocol.SetProtocol(this.req_energy_rank_info);
		this.Protocol.SetRequest(this.req_energy_rank_info ,C2SSproto.req_energy_rank_info_request);
		this.Protocol.SetResponse(this.req_energy_rank_info ,C2SSproto.req_energy_rank_info_response);

		this.Protocol.SetProtocol(this.req_exchange_mall);
		this.Protocol.SetRequest(this.req_exchange_mall ,C2SSproto.req_exchange_mall_request);
		this.Protocol.SetResponse(this.req_exchange_mall ,C2SSproto.req_exchange_mall_response);

		this.Protocol.SetProtocol(this.req_fish_expert);
		this.Protocol.SetRequest(this.req_fish_expert ,C2SSproto.req_fish_expert_request);
		this.Protocol.SetResponse(this.req_fish_expert ,C2SSproto.req_fish_expert_response);

		this.Protocol.SetProtocol(this.req_fish_expert_reward);
		this.Protocol.SetRequest(this.req_fish_expert_reward ,C2SSproto.req_fish_expert_reward_request);
		this.Protocol.SetResponse(this.req_fish_expert_reward ,C2SSproto.req_fish_expert_reward_response);

		this.Protocol.SetProtocol(this.req_gift);
		this.Protocol.SetRequest(this.req_gift ,C2SSproto.req_gift_request);
		this.Protocol.SetResponse(this.req_gift ,C2SSproto.req_gift_response);

		this.Protocol.SetProtocol(this.req_gold_fish_lottery);
		this.Protocol.SetRequest(this.req_gold_fish_lottery ,C2SSproto.req_gold_fish_lottery_request);
		this.Protocol.SetResponse(this.req_gold_fish_lottery ,C2SSproto.req_gold_fish_lottery_response);

		this.Protocol.SetProtocol(this.req_grow_up_activity);
		this.Protocol.SetRequest(this.req_grow_up_activity ,C2SSproto.req_grow_up_activity_request);
		this.Protocol.SetResponse(this.req_grow_up_activity ,C2SSproto.req_grow_up_activity_response);

		this.Protocol.SetProtocol(this.req_grow_up_task_reward);
		this.Protocol.SetRequest(this.req_grow_up_task_reward ,C2SSproto.req_grow_up_task_reward_request);
		this.Protocol.SetResponse(this.req_grow_up_task_reward ,C2SSproto.req_grow_up_task_reward_response);

		this.Protocol.SetProtocol(this.req_last_energy_rank_info);
		this.Protocol.SetRequest(this.req_last_energy_rank_info ,C2SSproto.req_last_energy_rank_info_request);
		this.Protocol.SetResponse(this.req_last_energy_rank_info ,C2SSproto.req_last_energy_rank_info_response);

		this.Protocol.SetProtocol(this.req_last_rank_info);
		this.Protocol.SetRequest(this.req_last_rank_info ,C2SSproto.req_last_rank_info_request);
		this.Protocol.SetResponse(this.req_last_rank_info ,C2SSproto.req_last_rank_info_response);

		this.Protocol.SetProtocol(this.req_liveness_reward);
		this.Protocol.SetRequest(this.req_liveness_reward ,C2SSproto.req_liveness_reward_request);
		this.Protocol.SetResponse(this.req_liveness_reward ,C2SSproto.req_liveness_reward_response);

		this.Protocol.SetProtocol(this.req_lock_fish);
		this.Protocol.SetRequest(this.req_lock_fish ,C2SSproto.req_lock_fish_request);
		this.Protocol.SetResponse(this.req_lock_fish ,C2SSproto.req_lock_fish_response);

		this.Protocol.SetProtocol(this.req_lottery_list);
		this.Protocol.SetRequest(this.req_lottery_list ,C2SSproto.req_lottery_list_request);
		this.Protocol.SetResponse(this.req_lottery_list ,C2SSproto.req_lottery_list_response);

		this.Protocol.SetProtocol(this.req_mall_exchange_info);
		this.Protocol.SetRequest(this.req_mall_exchange_info ,C2SSproto.req_mall_exchange_info_request);
		this.Protocol.SetResponse(this.req_mall_exchange_info ,C2SSproto.req_mall_exchange_info_response);

		this.Protocol.SetProtocol(this.req_mall_info);
		this.Protocol.SetRequest(this.req_mall_info ,C2SSproto.req_mall_info_request);

		this.Protocol.SetProtocol(this.req_mark_gift);
		this.Protocol.SetRequest(this.req_mark_gift ,C2SSproto.req_mark_gift_request);

		this.Protocol.SetProtocol(this.req_mobile_package);
		this.Protocol.SetRequest(this.req_mobile_package ,C2SSproto.req_mobile_package_request);
		this.Protocol.SetResponse(this.req_mobile_package ,C2SSproto.req_mobile_package_response);

		this.Protocol.SetProtocol(this.req_monthly_card_ui_data);
		this.Protocol.SetRequest(this.req_monthly_card_ui_data ,C2SSproto.req_monthly_card_ui_data_request);
		this.Protocol.SetResponse(this.req_monthly_card_ui_data ,C2SSproto.req_monthly_card_ui_data_response);

		this.Protocol.SetProtocol(this.req_mul_activity);
		this.Protocol.SetRequest(this.req_mul_activity ,C2SSproto.req_mul_activity_request);
		this.Protocol.SetResponse(this.req_mul_activity ,C2SSproto.req_mul_activity_response);

		this.Protocol.SetProtocol(this.req_my_lucky_purch_record);
		this.Protocol.SetRequest(this.req_my_lucky_purch_record ,C2SSproto.req_my_lucky_purch_record_request);
		this.Protocol.SetResponse(this.req_my_lucky_purch_record ,C2SSproto.req_my_lucky_purch_record_response);

		this.Protocol.SetProtocol(this.req_need_pop_interface);
		this.Protocol.SetRequest(this.req_need_pop_interface ,C2SSproto.req_need_pop_interface_request);
		this.Protocol.SetResponse(this.req_need_pop_interface ,C2SSproto.req_need_pop_interface_response);

		this.Protocol.SetProtocol(this.req_new_sign_in_info);
		this.Protocol.SetRequest(this.req_new_sign_in_info ,C2SSproto.req_new_sign_in_info_request);
		this.Protocol.SetResponse(this.req_new_sign_in_info ,C2SSproto.req_new_sign_in_info_response);

		this.Protocol.SetProtocol(this.req_ninja_round);
		this.Protocol.SetRequest(this.req_ninja_round ,C2SSproto.req_ninja_round_request);
		this.Protocol.SetResponse(this.req_ninja_round ,C2SSproto.req_ninja_round_response);

		this.Protocol.SetProtocol(this.req_ninja_uncover);
		this.Protocol.SetRequest(this.req_ninja_uncover ,C2SSproto.req_ninja_uncover_request);
		this.Protocol.SetResponse(this.req_ninja_uncover ,C2SSproto.req_ninja_uncover_response);

		this.Protocol.SetProtocol(this.req_open_backpack);
		this.Protocol.SetRequest(this.req_open_backpack ,C2SSproto.req_open_backpack_request);

		this.Protocol.SetProtocol(this.req_payment_order);
		this.Protocol.SetRequest(this.req_payment_order ,C2SSproto.req_payment_order_request);
		this.Protocol.SetResponse(this.req_payment_order ,C2SSproto.req_payment_order_response);

		this.Protocol.SetProtocol(this.req_purch_lucky_purch);
		this.Protocol.SetRequest(this.req_purch_lucky_purch ,C2SSproto.req_purch_lucky_purch_request);
		this.Protocol.SetResponse(this.req_purch_lucky_purch ,C2SSproto.req_purch_lucky_purch_response);

		this.Protocol.SetProtocol(this.req_quick_task_reward);
		this.Protocol.SetRequest(this.req_quick_task_reward ,C2SSproto.req_quick_task_reward_request);
		this.Protocol.SetResponse(this.req_quick_task_reward ,C2SSproto.req_quick_task_reward_response);

		this.Protocol.SetProtocol(this.req_rank_config);
		this.Protocol.SetRequest(this.req_rank_config ,C2SSproto.req_rank_config_request);
		this.Protocol.SetResponse(this.req_rank_config ,C2SSproto.req_rank_config_response);

		this.Protocol.SetProtocol(this.req_rank_info);
		this.Protocol.SetRequest(this.req_rank_info ,C2SSproto.req_rank_info_request);
		this.Protocol.SetResponse(this.req_rank_info ,C2SSproto.req_rank_info_response);

		this.Protocol.SetProtocol(this.req_receive_monthly_card);
		this.Protocol.SetRequest(this.req_receive_monthly_card ,C2SSproto.req_receive_monthly_card_request);
		this.Protocol.SetResponse(this.req_receive_monthly_card ,C2SSproto.req_receive_monthly_card_response);

		this.Protocol.SetProtocol(this.req_red_packet_exchange);
		this.Protocol.SetRequest(this.req_red_packet_exchange ,C2SSproto.req_red_packet_exchange_request);
		this.Protocol.SetResponse(this.req_red_packet_exchange ,C2SSproto.req_red_packet_exchange_response);

		this.Protocol.SetProtocol(this.req_red_packet_exchange_info);
		this.Protocol.SetRequest(this.req_red_packet_exchange_info ,C2SSproto.req_red_packet_exchange_info_request);
		this.Protocol.SetResponse(this.req_red_packet_exchange_info ,C2SSproto.req_red_packet_exchange_info_response);

		this.Protocol.SetProtocol(this.req_red_packet_reward);
		this.Protocol.SetRequest(this.req_red_packet_reward ,C2SSproto.req_red_packet_reward_request);
		this.Protocol.SetResponse(this.req_red_packet_reward ,C2SSproto.req_red_packet_reward_response);

		this.Protocol.SetProtocol(this.req_reward_catch_fish_expert);
		this.Protocol.SetRequest(this.req_reward_catch_fish_expert ,C2SSproto.req_reward_catch_fish_expert_request);
		this.Protocol.SetResponse(this.req_reward_catch_fish_expert ,C2SSproto.req_reward_catch_fish_expert_response);

		this.Protocol.SetProtocol(this.req_reward_record_lucky_purch);
		this.Protocol.SetRequest(this.req_reward_record_lucky_purch ,C2SSproto.req_reward_record_lucky_purch_request);
		this.Protocol.SetResponse(this.req_reward_record_lucky_purch ,C2SSproto.req_reward_record_lucky_purch_response);

		this.Protocol.SetProtocol(this.req_room_act_rank_info);
		this.Protocol.SetRequest(this.req_room_act_rank_info ,C2SSproto.req_room_act_rank_info_request);
		this.Protocol.SetResponse(this.req_room_act_rank_info ,C2SSproto.req_room_act_rank_info_response);

		this.Protocol.SetProtocol(this.req_room_info);
		this.Protocol.SetRequest(this.req_room_info ,C2SSproto.req_room_info_request);
		this.Protocol.SetResponse(this.req_room_info ,C2SSproto.req_room_info_response);

		this.Protocol.SetProtocol(this.req_room_list);
		this.Protocol.SetRequest(this.req_room_list ,C2SSproto.req_room_list_request);
		this.Protocol.SetResponse(this.req_room_list ,C2SSproto.req_room_list_response);

		this.Protocol.SetProtocol(this.req_sand_task_info);
		this.Protocol.SetRequest(this.req_sand_task_info ,C2SSproto.req_sand_task_info_request);
		this.Protocol.SetResponse(this.req_sand_task_info ,C2SSproto.req_sand_task_info_response);

		this.Protocol.SetProtocol(this.req_sand_task_reward);
		this.Protocol.SetRequest(this.req_sand_task_reward ,C2SSproto.req_sand_task_reward_request);
		this.Protocol.SetResponse(this.req_sand_task_reward ,C2SSproto.req_sand_task_reward_response);

		this.Protocol.SetProtocol(this.req_server_time);
		this.Protocol.SetRequest(this.req_server_time ,C2SSproto.req_server_time_request);
		this.Protocol.SetResponse(this.req_server_time ,C2SSproto.req_server_time_response);

		this.Protocol.SetProtocol(this.req_take_gift);
		this.Protocol.SetRequest(this.req_take_gift ,C2SSproto.req_take_gift_request);
		this.Protocol.SetResponse(this.req_take_gift ,C2SSproto.req_take_gift_response);

		this.Protocol.SetProtocol(this.req_task_list);
		this.Protocol.SetRequest(this.req_task_list ,C2SSproto.req_task_list_request);
		this.Protocol.SetResponse(this.req_task_list ,C2SSproto.req_task_list_response);

		this.Protocol.SetProtocol(this.req_task_reward);
		this.Protocol.SetRequest(this.req_task_reward ,C2SSproto.req_task_reward_request);
		this.Protocol.SetResponse(this.req_task_reward ,C2SSproto.req_task_reward_response);

		this.Protocol.SetProtocol(this.req_today_give_prop_info);
		this.Protocol.SetRequest(this.req_today_give_prop_info ,C2SSproto.req_today_give_prop_info_request);
		this.Protocol.SetResponse(this.req_today_give_prop_info ,C2SSproto.req_today_give_prop_info_response);

		this.Protocol.SetProtocol(this.req_upgrade_battery);
		this.Protocol.SetRequest(this.req_upgrade_battery ,C2SSproto.req_upgrade_battery_request);
		this.Protocol.SetResponse(this.req_upgrade_battery ,C2SSproto.req_upgrade_battery_response);

		this.Protocol.SetProtocol(this.req_user_exchanged_info);
		this.Protocol.SetRequest(this.req_user_exchanged_info ,C2SSproto.req_user_exchanged_info_request);
		this.Protocol.SetResponse(this.req_user_exchanged_info ,C2SSproto.req_user_exchanged_info_response);

		this.Protocol.SetProtocol(this.req_vdaily_reward);
		this.Protocol.SetRequest(this.req_vdaily_reward ,C2SSproto.req_vdaily_reward_request);
		this.Protocol.SetResponse(this.req_vdaily_reward ,C2SSproto.req_vdaily_reward_response);

		this.Protocol.SetProtocol(this.req_write_inviter);
		this.Protocol.SetRequest(this.req_write_inviter ,C2SSproto.req_write_inviter_request);
		this.Protocol.SetResponse(this.req_write_inviter ,C2SSproto.req_write_inviter_response);

		this.Protocol.SetProtocol(this.request_bankrupt);
		this.Protocol.SetRequest(this.request_bankrupt ,C2SSproto.request_bankrupt_request);
		this.Protocol.SetResponse(this.request_bankrupt ,C2SSproto.request_bankrupt_response);

		this.Protocol.SetProtocol(this.request_purchase);
		this.Protocol.SetRequest(this.request_purchase ,C2SSproto.request_purchase_request);
		this.Protocol.SetResponse(this.request_purchase ,C2SSproto.request_purchase_response);

		this.Protocol.SetProtocol(this.request_update_rookie);
		this.Protocol.SetRequest(this.request_update_rookie ,C2SSproto.request_update_rookie_request);

		this.Protocol.SetProtocol(this.room_energy_exchange);
		this.Protocol.SetRequest(this.room_energy_exchange ,C2SSproto.room_energy_exchange_request);
		this.Protocol.SetResponse(this.room_energy_exchange ,C2SSproto.room_energy_exchange_response);

		this.Protocol.SetProtocol(this.room_quit);
		this.Protocol.SetRequest(this.room_quit ,C2SSproto.room_quit_request);
		this.Protocol.SetResponse(this.room_quit ,C2SSproto.room_quit_response);

		this.Protocol.SetProtocol(this.room_sign_up);
		this.Protocol.SetRequest(this.room_sign_up ,C2SSproto.room_sign_up_request);
		this.Protocol.SetResponse(this.room_sign_up ,C2SSproto.room_sign_up_response);

		this.Protocol.SetProtocol(this.room_slots_luckydraw);
		this.Protocol.SetRequest(this.room_slots_luckydraw ,C2SSproto.room_slots_luckydraw_request);
		this.Protocol.SetResponse(this.room_slots_luckydraw ,C2SSproto.room_slots_luckydraw_response);

		this.Protocol.SetProtocol(this.send_sms_verification_code);
		this.Protocol.SetRequest(this.send_sms_verification_code ,C2SSproto.send_sms_verification_code_request);
		this.Protocol.SetResponse(this.send_sms_verification_code ,C2SSproto.send_sms_verification_code_response);

		this.Protocol.SetProtocol(this.set_activity_read);
		this.Protocol.SetRequest(this.set_activity_read ,C2SSproto.set_activity_read_request);

		this.Protocol.SetProtocol(this.set_newbie_guide_step);
		this.Protocol.SetRequest(this.set_newbie_guide_step ,C2SSproto.set_newbie_guide_step_request);
		this.Protocol.SetResponse(this.set_newbie_guide_step ,C2SSproto.set_newbie_guide_step_response);

		this.Protocol.SetProtocol(this.switch_equipment);
		this.Protocol.SetRequest(this.switch_equipment ,C2SSproto.switch_equipment_request);
		this.Protocol.SetResponse(this.switch_equipment ,C2SSproto.switch_equipment_response);

		this.Protocol.SetProtocol(this.sync_machine_storm_gold);
		this.Protocol.SetRequest(this.sync_machine_storm_gold ,C2SSproto.sync_machine_storm_gold_request);

		this.Protocol.SetProtocol(this.sync_user_info);
		this.Protocol.SetRequest(this.sync_user_info ,C2SSproto.sync_user_info_request);
		this.Protocol.SetResponse(this.sync_user_info ,C2SSproto.sync_user_info_response);

		this.Protocol.SetProtocol(this.take_mail_reward);
		this.Protocol.SetRequest(this.take_mail_reward ,C2SSproto.take_mail_reward_request);
		this.Protocol.SetResponse(this.take_mail_reward ,C2SSproto.take_mail_reward_response);

		this.Protocol.SetProtocol(this.unbind_phone_number);
		this.Protocol.SetRequest(this.unbind_phone_number ,C2SSproto.unbind_phone_number_request);
		this.Protocol.SetResponse(this.unbind_phone_number ,C2SSproto.unbind_phone_number_response);

		this.Protocol.SetProtocol(this.update_user_bio);
		this.Protocol.SetRequest(this.update_user_bio ,C2SSproto.update_user_bio_request);
		this.Protocol.SetResponse(this.update_user_bio ,C2SSproto.update_user_bio_response);

		this.Protocol.SetProtocol(this.use_prop);
		this.Protocol.SetRequest(this.use_prop ,C2SSproto.use_prop_request);
		this.Protocol.SetResponse(this.use_prop ,C2SSproto.use_prop_response);

		this.Protocol.SetProtocol(this.use_spec_bullet);
		this.Protocol.SetRequest(this.use_spec_bullet ,C2SSproto.use_spec_bullet_request);
		this.Protocol.SetResponse(this.use_spec_bullet ,C2SSproto.use_spec_bullet_response);

		this.Protocol.SetProtocol(this.user_feedback);
		this.Protocol.SetRequest(this.user_feedback ,C2SSproto.user_feedback_request);
		this.Protocol.SetResponse(this.user_feedback ,C2SSproto.user_feedback_response);

		this.Protocol.SetProtocol(this.verify_phone_number);
		this.Protocol.SetRequest(this.verify_phone_number ,C2SSproto.verify_phone_number_request);
		this.Protocol.SetResponse(this.verify_phone_number ,C2SSproto.verify_phone_number_response);

	}

	public get bind_phone_number_Request(): C2SSproto.bind_phone_number_request {
		return <C2SSproto.bind_phone_number_request>this.Protocol.GenRequest(this.bind_phone_number);
	}

	public get bind_phone_number_Response(): C2SSproto.bind_phone_number_response {
		return <C2SSproto.bind_phone_number_response>this.Protocol.GenResponse(this.bind_phone_number);
	}

	public get bomb_fish_click_Request(): C2SSproto.bomb_fish_click_request {
		return <C2SSproto.bomb_fish_click_request>this.Protocol.GenRequest(this.bomb_fish_click);
	}

	public get delete_mail_Request(): C2SSproto.delete_mail_request {
		return <C2SSproto.delete_mail_request>this.Protocol.GenRequest(this.delete_mail);
	}

	public get delete_mail_Response(): C2SSproto.delete_mail_response {
		return <C2SSproto.delete_mail_response>this.Protocol.GenResponse(this.delete_mail);
	}

	public get eat_fish_Request(): C2SSproto.eat_fish_request {
		return <C2SSproto.eat_fish_request>this.Protocol.GenRequest(this.eat_fish);
	}

	public get fire_Request(): C2SSproto.fire_request {
		return <C2SSproto.fire_request>this.Protocol.GenRequest(this.fire);
	}

	public get fish_net_Request(): C2SSproto.fish_net_request {
		return <C2SSproto.fish_net_request>this.Protocol.GenRequest(this.fish_net);
	}

	public get fish_net_Response(): C2SSproto.fish_net_response {
		return <C2SSproto.fish_net_response>this.Protocol.GenResponse(this.fish_net);
	}

	public get func_penetration_shoot_Request(): C2SSproto.func_penetration_shoot_request {
		return <C2SSproto.func_penetration_shoot_request>this.Protocol.GenRequest(this.func_penetration_shoot);
	}

	public get func_penetration_shoot_Response(): C2SSproto.func_penetration_shoot_response {
		return <C2SSproto.func_penetration_shoot_response>this.Protocol.GenResponse(this.func_penetration_shoot);
	}

	public get function_timer_start_Request(): C2SSproto.function_timer_start_request {
		return <C2SSproto.function_timer_start_request>this.Protocol.GenRequest(this.function_timer_start);
	}

	public get function_timer_start_Response(): C2SSproto.function_timer_start_response {
		return <C2SSproto.function_timer_start_response>this.Protocol.GenResponse(this.function_timer_start);
	}

	public get get_Request(): C2SSproto.get_request {
		return <C2SSproto.get_request>this.Protocol.GenRequest(this.get);
	}

	public get get_Response(): C2SSproto.get_response {
		return <C2SSproto.get_response>this.Protocol.GenResponse(this.get);
	}

	public get get_fast_login_account_Request(): C2SSproto.get_fast_login_account_request {
		return <C2SSproto.get_fast_login_account_request>this.Protocol.GenRequest(this.get_fast_login_account);
	}

	public get get_fast_login_account_Response(): C2SSproto.get_fast_login_account_response {
		return <C2SSproto.get_fast_login_account_response>this.Protocol.GenResponse(this.get_fast_login_account);
	}

	public get get_mail_list_Request(): C2SSproto.get_mail_list_request {
		return <C2SSproto.get_mail_list_request>this.Protocol.GenRequest(this.get_mail_list);
	}

	public get get_mail_list_Response(): C2SSproto.get_mail_list_response {
		return <C2SSproto.get_mail_list_response>this.Protocol.GenResponse(this.get_mail_list);
	}

	public get get_newbie_guide_progress_Request(): C2SSproto.get_newbie_guide_progress_request {
		return <C2SSproto.get_newbie_guide_progress_request>this.Protocol.GenRequest(this.get_newbie_guide_progress);
	}

	public get get_newbie_guide_progress_Response(): C2SSproto.get_newbie_guide_progress_response {
		return <C2SSproto.get_newbie_guide_progress_response>this.Protocol.GenResponse(this.get_newbie_guide_progress);
	}

	public get get_redpoint_Request(): C2SSproto.get_redpoint_request {
		return <C2SSproto.get_redpoint_request>this.Protocol.GenRequest(this.get_redpoint);
	}

	public get get_redpoint_Response(): C2SSproto.get_redpoint_response {
		return <C2SSproto.get_redpoint_response>this.Protocol.GenResponse(this.get_redpoint);
	}

	public get get_user_bio_Request(): C2SSproto.get_user_bio_request {
		return <C2SSproto.get_user_bio_request>this.Protocol.GenRequest(this.get_user_bio);
	}

	public get get_user_bio_Response(): C2SSproto.get_user_bio_response {
		return <C2SSproto.get_user_bio_response>this.Protocol.GenResponse(this.get_user_bio);
	}

	public get get_user_equipment_Request(): C2SSproto.get_user_equipment_request {
		return <C2SSproto.get_user_equipment_request>this.Protocol.GenRequest(this.get_user_equipment);
	}

	public get get_user_equipment_Response(): C2SSproto.get_user_equipment_response {
		return <C2SSproto.get_user_equipment_response>this.Protocol.GenResponse(this.get_user_equipment);
	}

	public get give_prop_2_others_Request(): C2SSproto.give_prop_2_others_request {
		return <C2SSproto.give_prop_2_others_request>this.Protocol.GenRequest(this.give_prop_2_others);
	}

	public get give_prop_2_others_Response(): C2SSproto.give_prop_2_others_response {
		return <C2SSproto.give_prop_2_others_response>this.Protocol.GenResponse(this.give_prop_2_others);
	}

	public get gm_Request(): C2SSproto.gm_request {
		return <C2SSproto.gm_request>this.Protocol.GenRequest(this.gm);
	}

	public get gm_Response(): C2SSproto.gm_response {
		return <C2SSproto.gm_response>this.Protocol.GenResponse(this.gm);
	}

	public get handshake_Request(): C2SSproto.handshake_request {
		return <C2SSproto.handshake_request>this.Protocol.GenRequest(this.handshake);
	}

	public get heartbeat_Request(): C2SSproto.heartbeat_request {
		return <C2SSproto.heartbeat_request>this.Protocol.GenRequest(this.heartbeat);
	}

	public get heartbeat_Response(): C2SSproto.heartbeat_response {
		return <C2SSproto.heartbeat_response>this.Protocol.GenResponse(this.heartbeat);
	}

	public get login_Request(): C2SSproto.login_request {
		return <C2SSproto.login_request>this.Protocol.GenRequest(this.login);
	}

	public get login_Response(): C2SSproto.login_response {
		return <C2SSproto.login_response>this.Protocol.GenResponse(this.login);
	}

	public get modify_nickname_Request(): C2SSproto.modify_nickname_request {
		return <C2SSproto.modify_nickname_request>this.Protocol.GenRequest(this.modify_nickname);
	}

	public get modify_nickname_Response(): C2SSproto.modify_nickname_response {
		return <C2SSproto.modify_nickname_response>this.Protocol.GenResponse(this.modify_nickname);
	}

	public get open_mail_Request(): C2SSproto.open_mail_request {
		return <C2SSproto.open_mail_request>this.Protocol.GenRequest(this.open_mail);
	}

	public get open_mail_Response(): C2SSproto.open_mail_response {
		return <C2SSproto.open_mail_response>this.Protocol.GenResponse(this.open_mail);
	}

	public get quick_sign_up_Request(): C2SSproto.quick_sign_up_request {
		return <C2SSproto.quick_sign_up_request>this.Protocol.GenRequest(this.quick_sign_up);
	}

	public get quick_sign_up_Response(): C2SSproto.quick_sign_up_response {
		return <C2SSproto.quick_sign_up_response>this.Protocol.GenResponse(this.quick_sign_up);
	}

	public get recycle_prop_Request(): C2SSproto.recycle_prop_request {
		return <C2SSproto.recycle_prop_request>this.Protocol.GenRequest(this.recycle_prop);
	}

	public get recycle_prop_Response(): C2SSproto.recycle_prop_response {
		return <C2SSproto.recycle_prop_response>this.Protocol.GenResponse(this.recycle_prop);
	}

	public get req_activity_cfg_Request(): C2SSproto.req_activity_cfg_request {
		return <C2SSproto.req_activity_cfg_request>this.Protocol.GenRequest(this.req_activity_cfg);
	}

	public get req_activity_cfg_Response(): C2SSproto.req_activity_cfg_response {
		return <C2SSproto.req_activity_cfg_response>this.Protocol.GenResponse(this.req_activity_cfg);
	}

	public get req_activity_reward_Request(): C2SSproto.req_activity_reward_request {
		return <C2SSproto.req_activity_reward_request>this.Protocol.GenRequest(this.req_activity_reward);
	}

	public get req_activity_reward_Response(): C2SSproto.req_activity_reward_response {
		return <C2SSproto.req_activity_reward_response>this.Protocol.GenResponse(this.req_activity_reward);
	}

	public get req_activity_tab_list_Request(): C2SSproto.req_activity_tab_list_request {
		return <C2SSproto.req_activity_tab_list_request>this.Protocol.GenRequest(this.req_activity_tab_list);
	}

	public get req_activity_tab_list_Response(): C2SSproto.req_activity_tab_list_response {
		return <C2SSproto.req_activity_tab_list_response>this.Protocol.GenResponse(this.req_activity_tab_list);
	}

	public get req_backpack_data_Response(): C2SSproto.req_backpack_data_response {
		return <C2SSproto.req_backpack_data_response>this.Protocol.GenResponse(this.req_backpack_data);
	}

	public get req_battery_Request(): C2SSproto.req_battery_request {
		return <C2SSproto.req_battery_request>this.Protocol.GenRequest(this.req_battery);
	}

	public get req_battery_Response(): C2SSproto.req_battery_response {
		return <C2SSproto.req_battery_response>this.Protocol.GenResponse(this.req_battery);
	}

	public get req_buy_gos_Request(): C2SSproto.req_buy_gos_request {
		return <C2SSproto.req_buy_gos_request>this.Protocol.GenRequest(this.req_buy_gos);
	}

	public get req_buy_gos_Response(): C2SSproto.req_buy_gos_response {
		return <C2SSproto.req_buy_gos_response>this.Protocol.GenResponse(this.req_buy_gos);
	}

	public get req_buy_monthly_card_Request(): C2SSproto.req_buy_monthly_card_request {
		return <C2SSproto.req_buy_monthly_card_request>this.Protocol.GenRequest(this.req_buy_monthly_card);
	}

	public get req_buy_monthly_card_Response(): C2SSproto.req_buy_monthly_card_response {
		return <C2SSproto.req_buy_monthly_card_response>this.Protocol.GenResponse(this.req_buy_monthly_card);
	}

	public get req_cannon_reward_Request(): C2SSproto.req_cannon_reward_request {
		return <C2SSproto.req_cannon_reward_request>this.Protocol.GenRequest(this.req_cannon_reward);
	}

	public get req_cannon_reward_Response(): C2SSproto.req_cannon_reward_response {
		return <C2SSproto.req_cannon_reward_response>this.Protocol.GenResponse(this.req_cannon_reward);
	}

	public get req_catch_fish_expert_info_Request(): C2SSproto.req_catch_fish_expert_info_request {
		return <C2SSproto.req_catch_fish_expert_info_request>this.Protocol.GenRequest(this.req_catch_fish_expert_info);
	}

	public get req_catch_fish_expert_info_Response(): C2SSproto.req_catch_fish_expert_info_response {
		return <C2SSproto.req_catch_fish_expert_info_response>this.Protocol.GenResponse(this.req_catch_fish_expert_info);
	}

	public get req_cd_key_reward_Request(): C2SSproto.req_cd_key_reward_request {
		return <C2SSproto.req_cd_key_reward_request>this.Protocol.GenRequest(this.req_cd_key_reward);
	}

	public get req_cd_key_reward_Response(): C2SSproto.req_cd_key_reward_response {
		return <C2SSproto.req_cd_key_reward_response>this.Protocol.GenResponse(this.req_cd_key_reward);
	}

	public get req_change_cannon_multiple_Request(): C2SSproto.req_change_cannon_multiple_request {
		return <C2SSproto.req_change_cannon_multiple_request>this.Protocol.GenRequest(this.req_change_cannon_multiple);
	}

	public get req_change_cannon_multiple_Response(): C2SSproto.req_change_cannon_multiple_response {
		return <C2SSproto.req_change_cannon_multiple_response>this.Protocol.GenResponse(this.req_change_cannon_multiple);
	}

	public get req_click_mall_info_Request(): C2SSproto.req_click_mall_info_request {
		return <C2SSproto.req_click_mall_info_request>this.Protocol.GenRequest(this.req_click_mall_info);
	}

	public get req_click_mall_info_Response(): C2SSproto.req_click_mall_info_response {
		return <C2SSproto.req_click_mall_info_response>this.Protocol.GenResponse(this.req_click_mall_info);
	}

	public get req_click_pop_interface_Request(): C2SSproto.req_click_pop_interface_request {
		return <C2SSproto.req_click_pop_interface_request>this.Protocol.GenRequest(this.req_click_pop_interface);
	}

	public get req_com_daily_share_Request(): C2SSproto.req_com_daily_share_request {
		return <C2SSproto.req_com_daily_share_request>this.Protocol.GenRequest(this.req_com_daily_share);
	}

	public get req_com_daily_share_Response(): C2SSproto.req_com_daily_share_response {
		return <C2SSproto.req_com_daily_share_response>this.Protocol.GenResponse(this.req_com_daily_share);
	}

	public get req_common_activity_info_Request(): C2SSproto.req_common_activity_info_request {
		return <C2SSproto.req_common_activity_info_request>this.Protocol.GenRequest(this.req_common_activity_info);
	}

	public get req_common_activity_info_Response(): C2SSproto.req_common_activity_info_response {
		return <C2SSproto.req_common_activity_info_response>this.Protocol.GenResponse(this.req_common_activity_info);
	}

	public get req_common_activity_reward_Request(): C2SSproto.req_common_activity_reward_request {
		return <C2SSproto.req_common_activity_reward_request>this.Protocol.GenRequest(this.req_common_activity_reward);
	}

	public get req_common_activity_reward_Response(): C2SSproto.req_common_activity_reward_response {
		return <C2SSproto.req_common_activity_reward_response>this.Protocol.GenResponse(this.req_common_activity_reward);
	}

	public get req_do_lottery_Request(): C2SSproto.req_do_lottery_request {
		return <C2SSproto.req_do_lottery_request>this.Protocol.GenRequest(this.req_do_lottery);
	}

	public get req_do_lottery_Response(): C2SSproto.req_do_lottery_response {
		return <C2SSproto.req_do_lottery_response>this.Protocol.GenResponse(this.req_do_lottery);
	}

	public get req_do_lottery_gold_fish_Request(): C2SSproto.req_do_lottery_gold_fish_request {
		return <C2SSproto.req_do_lottery_gold_fish_request>this.Protocol.GenRequest(this.req_do_lottery_gold_fish);
	}

	public get req_do_lottery_gold_fish_Response(): C2SSproto.req_do_lottery_gold_fish_response {
		return <C2SSproto.req_do_lottery_gold_fish_response>this.Protocol.GenResponse(this.req_do_lottery_gold_fish);
	}

	public get req_do_new_sign_in_Request(): C2SSproto.req_do_new_sign_in_request {
		return <C2SSproto.req_do_new_sign_in_request>this.Protocol.GenRequest(this.req_do_new_sign_in);
	}

	public get req_do_new_sign_in_Response(): C2SSproto.req_do_new_sign_in_response {
		return <C2SSproto.req_do_new_sign_in_response>this.Protocol.GenResponse(this.req_do_new_sign_in);
	}

	public get req_do_select_sand_task_Request(): C2SSproto.req_do_select_sand_task_request {
		return <C2SSproto.req_do_select_sand_task_request>this.Protocol.GenRequest(this.req_do_select_sand_task);
	}

	public get req_do_select_sand_task_Response(): C2SSproto.req_do_select_sand_task_response {
		return <C2SSproto.req_do_select_sand_task_response>this.Protocol.GenResponse(this.req_do_select_sand_task);
	}

	public get req_energy_factor_unlock_Request(): C2SSproto.req_energy_factor_unlock_request {
		return <C2SSproto.req_energy_factor_unlock_request>this.Protocol.GenRequest(this.req_energy_factor_unlock);
	}

	public get req_energy_factor_unlock_Response(): C2SSproto.req_energy_factor_unlock_response {
		return <C2SSproto.req_energy_factor_unlock_response>this.Protocol.GenResponse(this.req_energy_factor_unlock);
	}

	public get req_energy_rank_info_Request(): C2SSproto.req_energy_rank_info_request {
		return <C2SSproto.req_energy_rank_info_request>this.Protocol.GenRequest(this.req_energy_rank_info);
	}

	public get req_energy_rank_info_Response(): C2SSproto.req_energy_rank_info_response {
		return <C2SSproto.req_energy_rank_info_response>this.Protocol.GenResponse(this.req_energy_rank_info);
	}

	public get req_exchange_mall_Request(): C2SSproto.req_exchange_mall_request {
		return <C2SSproto.req_exchange_mall_request>this.Protocol.GenRequest(this.req_exchange_mall);
	}

	public get req_exchange_mall_Response(): C2SSproto.req_exchange_mall_response {
		return <C2SSproto.req_exchange_mall_response>this.Protocol.GenResponse(this.req_exchange_mall);
	}

	public get req_fish_expert_Request(): C2SSproto.req_fish_expert_request {
		return <C2SSproto.req_fish_expert_request>this.Protocol.GenRequest(this.req_fish_expert);
	}

	public get req_fish_expert_Response(): C2SSproto.req_fish_expert_response {
		return <C2SSproto.req_fish_expert_response>this.Protocol.GenResponse(this.req_fish_expert);
	}

	public get req_fish_expert_reward_Request(): C2SSproto.req_fish_expert_reward_request {
		return <C2SSproto.req_fish_expert_reward_request>this.Protocol.GenRequest(this.req_fish_expert_reward);
	}

	public get req_fish_expert_reward_Response(): C2SSproto.req_fish_expert_reward_response {
		return <C2SSproto.req_fish_expert_reward_response>this.Protocol.GenResponse(this.req_fish_expert_reward);
	}

	public get req_gift_Request(): C2SSproto.req_gift_request {
		return <C2SSproto.req_gift_request>this.Protocol.GenRequest(this.req_gift);
	}

	public get req_gift_Response(): C2SSproto.req_gift_response {
		return <C2SSproto.req_gift_response>this.Protocol.GenResponse(this.req_gift);
	}

	public get req_gold_fish_lottery_Request(): C2SSproto.req_gold_fish_lottery_request {
		return <C2SSproto.req_gold_fish_lottery_request>this.Protocol.GenRequest(this.req_gold_fish_lottery);
	}

	public get req_gold_fish_lottery_Response(): C2SSproto.req_gold_fish_lottery_response {
		return <C2SSproto.req_gold_fish_lottery_response>this.Protocol.GenResponse(this.req_gold_fish_lottery);
	}

	public get req_grow_up_activity_Request(): C2SSproto.req_grow_up_activity_request {
		return <C2SSproto.req_grow_up_activity_request>this.Protocol.GenRequest(this.req_grow_up_activity);
	}

	public get req_grow_up_activity_Response(): C2SSproto.req_grow_up_activity_response {
		return <C2SSproto.req_grow_up_activity_response>this.Protocol.GenResponse(this.req_grow_up_activity);
	}

	public get req_grow_up_task_reward_Request(): C2SSproto.req_grow_up_task_reward_request {
		return <C2SSproto.req_grow_up_task_reward_request>this.Protocol.GenRequest(this.req_grow_up_task_reward);
	}

	public get req_grow_up_task_reward_Response(): C2SSproto.req_grow_up_task_reward_response {
		return <C2SSproto.req_grow_up_task_reward_response>this.Protocol.GenResponse(this.req_grow_up_task_reward);
	}

	public get req_last_energy_rank_info_Request(): C2SSproto.req_last_energy_rank_info_request {
		return <C2SSproto.req_last_energy_rank_info_request>this.Protocol.GenRequest(this.req_last_energy_rank_info);
	}

	public get req_last_energy_rank_info_Response(): C2SSproto.req_last_energy_rank_info_response {
		return <C2SSproto.req_last_energy_rank_info_response>this.Protocol.GenResponse(this.req_last_energy_rank_info);
	}

	public get req_last_rank_info_Request(): C2SSproto.req_last_rank_info_request {
		return <C2SSproto.req_last_rank_info_request>this.Protocol.GenRequest(this.req_last_rank_info);
	}

	public get req_last_rank_info_Response(): C2SSproto.req_last_rank_info_response {
		return <C2SSproto.req_last_rank_info_response>this.Protocol.GenResponse(this.req_last_rank_info);
	}

	public get req_liveness_reward_Request(): C2SSproto.req_liveness_reward_request {
		return <C2SSproto.req_liveness_reward_request>this.Protocol.GenRequest(this.req_liveness_reward);
	}

	public get req_liveness_reward_Response(): C2SSproto.req_liveness_reward_response {
		return <C2SSproto.req_liveness_reward_response>this.Protocol.GenResponse(this.req_liveness_reward);
	}

	public get req_lock_fish_Request(): C2SSproto.req_lock_fish_request {
		return <C2SSproto.req_lock_fish_request>this.Protocol.GenRequest(this.req_lock_fish);
	}

	public get req_lock_fish_Response(): C2SSproto.req_lock_fish_response {
		return <C2SSproto.req_lock_fish_response>this.Protocol.GenResponse(this.req_lock_fish);
	}

	public get req_lottery_list_Request(): C2SSproto.req_lottery_list_request {
		return <C2SSproto.req_lottery_list_request>this.Protocol.GenRequest(this.req_lottery_list);
	}

	public get req_lottery_list_Response(): C2SSproto.req_lottery_list_response {
		return <C2SSproto.req_lottery_list_response>this.Protocol.GenResponse(this.req_lottery_list);
	}

	public get req_mall_exchange_info_Request(): C2SSproto.req_mall_exchange_info_request {
		return <C2SSproto.req_mall_exchange_info_request>this.Protocol.GenRequest(this.req_mall_exchange_info);
	}

	public get req_mall_exchange_info_Response(): C2SSproto.req_mall_exchange_info_response {
		return <C2SSproto.req_mall_exchange_info_response>this.Protocol.GenResponse(this.req_mall_exchange_info);
	}

	public get req_mall_info_Request(): C2SSproto.req_mall_info_request {
		return <C2SSproto.req_mall_info_request>this.Protocol.GenRequest(this.req_mall_info);
	}

	public get req_mark_gift_Request(): C2SSproto.req_mark_gift_request {
		return <C2SSproto.req_mark_gift_request>this.Protocol.GenRequest(this.req_mark_gift);
	}

	public get req_mobile_package_Request(): C2SSproto.req_mobile_package_request {
		return <C2SSproto.req_mobile_package_request>this.Protocol.GenRequest(this.req_mobile_package);
	}

	public get req_mobile_package_Response(): C2SSproto.req_mobile_package_response {
		return <C2SSproto.req_mobile_package_response>this.Protocol.GenResponse(this.req_mobile_package);
	}

	public get req_monthly_card_ui_data_Request(): C2SSproto.req_monthly_card_ui_data_request {
		return <C2SSproto.req_monthly_card_ui_data_request>this.Protocol.GenRequest(this.req_monthly_card_ui_data);
	}

	public get req_monthly_card_ui_data_Response(): C2SSproto.req_monthly_card_ui_data_response {
		return <C2SSproto.req_monthly_card_ui_data_response>this.Protocol.GenResponse(this.req_monthly_card_ui_data);
	}

	public get req_mul_activity_Request(): C2SSproto.req_mul_activity_request {
		return <C2SSproto.req_mul_activity_request>this.Protocol.GenRequest(this.req_mul_activity);
	}

	public get req_mul_activity_Response(): C2SSproto.req_mul_activity_response {
		return <C2SSproto.req_mul_activity_response>this.Protocol.GenResponse(this.req_mul_activity);
	}

	public get req_my_lucky_purch_record_Request(): C2SSproto.req_my_lucky_purch_record_request {
		return <C2SSproto.req_my_lucky_purch_record_request>this.Protocol.GenRequest(this.req_my_lucky_purch_record);
	}

	public get req_my_lucky_purch_record_Response(): C2SSproto.req_my_lucky_purch_record_response {
		return <C2SSproto.req_my_lucky_purch_record_response>this.Protocol.GenResponse(this.req_my_lucky_purch_record);
	}

	public get req_need_pop_interface_Request(): C2SSproto.req_need_pop_interface_request {
		return <C2SSproto.req_need_pop_interface_request>this.Protocol.GenRequest(this.req_need_pop_interface);
	}

	public get req_need_pop_interface_Response(): C2SSproto.req_need_pop_interface_response {
		return <C2SSproto.req_need_pop_interface_response>this.Protocol.GenResponse(this.req_need_pop_interface);
	}

	public get req_new_sign_in_info_Request(): C2SSproto.req_new_sign_in_info_request {
		return <C2SSproto.req_new_sign_in_info_request>this.Protocol.GenRequest(this.req_new_sign_in_info);
	}

	public get req_new_sign_in_info_Response(): C2SSproto.req_new_sign_in_info_response {
		return <C2SSproto.req_new_sign_in_info_response>this.Protocol.GenResponse(this.req_new_sign_in_info);
	}

	public get req_ninja_round_Request(): C2SSproto.req_ninja_round_request {
		return <C2SSproto.req_ninja_round_request>this.Protocol.GenRequest(this.req_ninja_round);
	}

	public get req_ninja_round_Response(): C2SSproto.req_ninja_round_response {
		return <C2SSproto.req_ninja_round_response>this.Protocol.GenResponse(this.req_ninja_round);
	}

	public get req_ninja_uncover_Request(): C2SSproto.req_ninja_uncover_request {
		return <C2SSproto.req_ninja_uncover_request>this.Protocol.GenRequest(this.req_ninja_uncover);
	}

	public get req_ninja_uncover_Response(): C2SSproto.req_ninja_uncover_response {
		return <C2SSproto.req_ninja_uncover_response>this.Protocol.GenResponse(this.req_ninja_uncover);
	}

	public get req_open_backpack_Request(): C2SSproto.req_open_backpack_request {
		return <C2SSproto.req_open_backpack_request>this.Protocol.GenRequest(this.req_open_backpack);
	}

	public get req_payment_order_Request(): C2SSproto.req_payment_order_request {
		return <C2SSproto.req_payment_order_request>this.Protocol.GenRequest(this.req_payment_order);
	}

	public get req_payment_order_Response(): C2SSproto.req_payment_order_response {
		return <C2SSproto.req_payment_order_response>this.Protocol.GenResponse(this.req_payment_order);
	}

	public get req_purch_lucky_purch_Request(): C2SSproto.req_purch_lucky_purch_request {
		return <C2SSproto.req_purch_lucky_purch_request>this.Protocol.GenRequest(this.req_purch_lucky_purch);
	}

	public get req_purch_lucky_purch_Response(): C2SSproto.req_purch_lucky_purch_response {
		return <C2SSproto.req_purch_lucky_purch_response>this.Protocol.GenResponse(this.req_purch_lucky_purch);
	}

	public get req_quick_task_reward_Request(): C2SSproto.req_quick_task_reward_request {
		return <C2SSproto.req_quick_task_reward_request>this.Protocol.GenRequest(this.req_quick_task_reward);
	}

	public get req_quick_task_reward_Response(): C2SSproto.req_quick_task_reward_response {
		return <C2SSproto.req_quick_task_reward_response>this.Protocol.GenResponse(this.req_quick_task_reward);
	}

	public get req_rank_config_Request(): C2SSproto.req_rank_config_request {
		return <C2SSproto.req_rank_config_request>this.Protocol.GenRequest(this.req_rank_config);
	}

	public get req_rank_config_Response(): C2SSproto.req_rank_config_response {
		return <C2SSproto.req_rank_config_response>this.Protocol.GenResponse(this.req_rank_config);
	}

	public get req_rank_info_Request(): C2SSproto.req_rank_info_request {
		return <C2SSproto.req_rank_info_request>this.Protocol.GenRequest(this.req_rank_info);
	}

	public get req_rank_info_Response(): C2SSproto.req_rank_info_response {
		return <C2SSproto.req_rank_info_response>this.Protocol.GenResponse(this.req_rank_info);
	}

	public get req_receive_monthly_card_Request(): C2SSproto.req_receive_monthly_card_request {
		return <C2SSproto.req_receive_monthly_card_request>this.Protocol.GenRequest(this.req_receive_monthly_card);
	}

	public get req_receive_monthly_card_Response(): C2SSproto.req_receive_monthly_card_response {
		return <C2SSproto.req_receive_monthly_card_response>this.Protocol.GenResponse(this.req_receive_monthly_card);
	}

	public get req_red_packet_exchange_Request(): C2SSproto.req_red_packet_exchange_request {
		return <C2SSproto.req_red_packet_exchange_request>this.Protocol.GenRequest(this.req_red_packet_exchange);
	}

	public get req_red_packet_exchange_Response(): C2SSproto.req_red_packet_exchange_response {
		return <C2SSproto.req_red_packet_exchange_response>this.Protocol.GenResponse(this.req_red_packet_exchange);
	}

	public get req_red_packet_exchange_info_Request(): C2SSproto.req_red_packet_exchange_info_request {
		return <C2SSproto.req_red_packet_exchange_info_request>this.Protocol.GenRequest(this.req_red_packet_exchange_info);
	}

	public get req_red_packet_exchange_info_Response(): C2SSproto.req_red_packet_exchange_info_response {
		return <C2SSproto.req_red_packet_exchange_info_response>this.Protocol.GenResponse(this.req_red_packet_exchange_info);
	}

	public get req_red_packet_reward_Request(): C2SSproto.req_red_packet_reward_request {
		return <C2SSproto.req_red_packet_reward_request>this.Protocol.GenRequest(this.req_red_packet_reward);
	}

	public get req_red_packet_reward_Response(): C2SSproto.req_red_packet_reward_response {
		return <C2SSproto.req_red_packet_reward_response>this.Protocol.GenResponse(this.req_red_packet_reward);
	}

	public get req_reward_catch_fish_expert_Request(): C2SSproto.req_reward_catch_fish_expert_request {
		return <C2SSproto.req_reward_catch_fish_expert_request>this.Protocol.GenRequest(this.req_reward_catch_fish_expert);
	}

	public get req_reward_catch_fish_expert_Response(): C2SSproto.req_reward_catch_fish_expert_response {
		return <C2SSproto.req_reward_catch_fish_expert_response>this.Protocol.GenResponse(this.req_reward_catch_fish_expert);
	}

	public get req_reward_record_lucky_purch_Request(): C2SSproto.req_reward_record_lucky_purch_request {
		return <C2SSproto.req_reward_record_lucky_purch_request>this.Protocol.GenRequest(this.req_reward_record_lucky_purch);
	}

	public get req_reward_record_lucky_purch_Response(): C2SSproto.req_reward_record_lucky_purch_response {
		return <C2SSproto.req_reward_record_lucky_purch_response>this.Protocol.GenResponse(this.req_reward_record_lucky_purch);
	}

	public get req_room_act_rank_info_Request(): C2SSproto.req_room_act_rank_info_request {
		return <C2SSproto.req_room_act_rank_info_request>this.Protocol.GenRequest(this.req_room_act_rank_info);
	}

	public get req_room_act_rank_info_Response(): C2SSproto.req_room_act_rank_info_response {
		return <C2SSproto.req_room_act_rank_info_response>this.Protocol.GenResponse(this.req_room_act_rank_info);
	}

	public get req_room_info_Request(): C2SSproto.req_room_info_request {
		return <C2SSproto.req_room_info_request>this.Protocol.GenRequest(this.req_room_info);
	}

	public get req_room_info_Response(): C2SSproto.req_room_info_response {
		return <C2SSproto.req_room_info_response>this.Protocol.GenResponse(this.req_room_info);
	}

	public get req_room_list_Request(): C2SSproto.req_room_list_request {
		return <C2SSproto.req_room_list_request>this.Protocol.GenRequest(this.req_room_list);
	}

	public get req_room_list_Response(): C2SSproto.req_room_list_response {
		return <C2SSproto.req_room_list_response>this.Protocol.GenResponse(this.req_room_list);
	}

	public get req_sand_task_info_Request(): C2SSproto.req_sand_task_info_request {
		return <C2SSproto.req_sand_task_info_request>this.Protocol.GenRequest(this.req_sand_task_info);
	}

	public get req_sand_task_info_Response(): C2SSproto.req_sand_task_info_response {
		return <C2SSproto.req_sand_task_info_response>this.Protocol.GenResponse(this.req_sand_task_info);
	}

	public get req_sand_task_reward_Request(): C2SSproto.req_sand_task_reward_request {
		return <C2SSproto.req_sand_task_reward_request>this.Protocol.GenRequest(this.req_sand_task_reward);
	}

	public get req_sand_task_reward_Response(): C2SSproto.req_sand_task_reward_response {
		return <C2SSproto.req_sand_task_reward_response>this.Protocol.GenResponse(this.req_sand_task_reward);
	}

	public get req_server_time_Request(): C2SSproto.req_server_time_request {
		return <C2SSproto.req_server_time_request>this.Protocol.GenRequest(this.req_server_time);
	}

	public get req_server_time_Response(): C2SSproto.req_server_time_response {
		return <C2SSproto.req_server_time_response>this.Protocol.GenResponse(this.req_server_time);
	}

	public get req_take_gift_Request(): C2SSproto.req_take_gift_request {
		return <C2SSproto.req_take_gift_request>this.Protocol.GenRequest(this.req_take_gift);
	}

	public get req_take_gift_Response(): C2SSproto.req_take_gift_response {
		return <C2SSproto.req_take_gift_response>this.Protocol.GenResponse(this.req_take_gift);
	}

	public get req_task_list_Request(): C2SSproto.req_task_list_request {
		return <C2SSproto.req_task_list_request>this.Protocol.GenRequest(this.req_task_list);
	}

	public get req_task_list_Response(): C2SSproto.req_task_list_response {
		return <C2SSproto.req_task_list_response>this.Protocol.GenResponse(this.req_task_list);
	}

	public get req_task_reward_Request(): C2SSproto.req_task_reward_request {
		return <C2SSproto.req_task_reward_request>this.Protocol.GenRequest(this.req_task_reward);
	}

	public get req_task_reward_Response(): C2SSproto.req_task_reward_response {
		return <C2SSproto.req_task_reward_response>this.Protocol.GenResponse(this.req_task_reward);
	}

	public get req_today_give_prop_info_Request(): C2SSproto.req_today_give_prop_info_request {
		return <C2SSproto.req_today_give_prop_info_request>this.Protocol.GenRequest(this.req_today_give_prop_info);
	}

	public get req_today_give_prop_info_Response(): C2SSproto.req_today_give_prop_info_response {
		return <C2SSproto.req_today_give_prop_info_response>this.Protocol.GenResponse(this.req_today_give_prop_info);
	}

	public get req_upgrade_battery_Request(): C2SSproto.req_upgrade_battery_request {
		return <C2SSproto.req_upgrade_battery_request>this.Protocol.GenRequest(this.req_upgrade_battery);
	}

	public get req_upgrade_battery_Response(): C2SSproto.req_upgrade_battery_response {
		return <C2SSproto.req_upgrade_battery_response>this.Protocol.GenResponse(this.req_upgrade_battery);
	}

	public get req_user_exchanged_info_Request(): C2SSproto.req_user_exchanged_info_request {
		return <C2SSproto.req_user_exchanged_info_request>this.Protocol.GenRequest(this.req_user_exchanged_info);
	}

	public get req_user_exchanged_info_Response(): C2SSproto.req_user_exchanged_info_response {
		return <C2SSproto.req_user_exchanged_info_response>this.Protocol.GenResponse(this.req_user_exchanged_info);
	}

	public get req_vdaily_reward_Request(): C2SSproto.req_vdaily_reward_request {
		return <C2SSproto.req_vdaily_reward_request>this.Protocol.GenRequest(this.req_vdaily_reward);
	}

	public get req_vdaily_reward_Response(): C2SSproto.req_vdaily_reward_response {
		return <C2SSproto.req_vdaily_reward_response>this.Protocol.GenResponse(this.req_vdaily_reward);
	}

	public get req_write_inviter_Request(): C2SSproto.req_write_inviter_request {
		return <C2SSproto.req_write_inviter_request>this.Protocol.GenRequest(this.req_write_inviter);
	}

	public get req_write_inviter_Response(): C2SSproto.req_write_inviter_response {
		return <C2SSproto.req_write_inviter_response>this.Protocol.GenResponse(this.req_write_inviter);
	}

	public get request_bankrupt_Request(): C2SSproto.request_bankrupt_request {
		return <C2SSproto.request_bankrupt_request>this.Protocol.GenRequest(this.request_bankrupt);
	}

	public get request_bankrupt_Response(): C2SSproto.request_bankrupt_response {
		return <C2SSproto.request_bankrupt_response>this.Protocol.GenResponse(this.request_bankrupt);
	}

	public get request_purchase_Request(): C2SSproto.request_purchase_request {
		return <C2SSproto.request_purchase_request>this.Protocol.GenRequest(this.request_purchase);
	}

	public get request_purchase_Response(): C2SSproto.request_purchase_response {
		return <C2SSproto.request_purchase_response>this.Protocol.GenResponse(this.request_purchase);
	}

	public get request_update_rookie_Request(): C2SSproto.request_update_rookie_request {
		return <C2SSproto.request_update_rookie_request>this.Protocol.GenRequest(this.request_update_rookie);
	}

	public get room_energy_exchange_Request(): C2SSproto.room_energy_exchange_request {
		return <C2SSproto.room_energy_exchange_request>this.Protocol.GenRequest(this.room_energy_exchange);
	}

	public get room_energy_exchange_Response(): C2SSproto.room_energy_exchange_response {
		return <C2SSproto.room_energy_exchange_response>this.Protocol.GenResponse(this.room_energy_exchange);
	}

	public get room_quit_Request(): C2SSproto.room_quit_request {
		return <C2SSproto.room_quit_request>this.Protocol.GenRequest(this.room_quit);
	}

	public get room_quit_Response(): C2SSproto.room_quit_response {
		return <C2SSproto.room_quit_response>this.Protocol.GenResponse(this.room_quit);
	}

	public get room_sign_up_Request(): C2SSproto.room_sign_up_request {
		return <C2SSproto.room_sign_up_request>this.Protocol.GenRequest(this.room_sign_up);
	}

	public get room_sign_up_Response(): C2SSproto.room_sign_up_response {
		return <C2SSproto.room_sign_up_response>this.Protocol.GenResponse(this.room_sign_up);
	}

	public get room_slots_luckydraw_Request(): C2SSproto.room_slots_luckydraw_request {
		return <C2SSproto.room_slots_luckydraw_request>this.Protocol.GenRequest(this.room_slots_luckydraw);
	}

	public get room_slots_luckydraw_Response(): C2SSproto.room_slots_luckydraw_response {
		return <C2SSproto.room_slots_luckydraw_response>this.Protocol.GenResponse(this.room_slots_luckydraw);
	}

	public get send_sms_verification_code_Request(): C2SSproto.send_sms_verification_code_request {
		return <C2SSproto.send_sms_verification_code_request>this.Protocol.GenRequest(this.send_sms_verification_code);
	}

	public get send_sms_verification_code_Response(): C2SSproto.send_sms_verification_code_response {
		return <C2SSproto.send_sms_verification_code_response>this.Protocol.GenResponse(this.send_sms_verification_code);
	}

	public get set_activity_read_Request(): C2SSproto.set_activity_read_request {
		return <C2SSproto.set_activity_read_request>this.Protocol.GenRequest(this.set_activity_read);
	}

	public get set_newbie_guide_step_Request(): C2SSproto.set_newbie_guide_step_request {
		return <C2SSproto.set_newbie_guide_step_request>this.Protocol.GenRequest(this.set_newbie_guide_step);
	}

	public get set_newbie_guide_step_Response(): C2SSproto.set_newbie_guide_step_response {
		return <C2SSproto.set_newbie_guide_step_response>this.Protocol.GenResponse(this.set_newbie_guide_step);
	}

	public get switch_equipment_Request(): C2SSproto.switch_equipment_request {
		return <C2SSproto.switch_equipment_request>this.Protocol.GenRequest(this.switch_equipment);
	}

	public get switch_equipment_Response(): C2SSproto.switch_equipment_response {
		return <C2SSproto.switch_equipment_response>this.Protocol.GenResponse(this.switch_equipment);
	}

	public get sync_machine_storm_gold_Request(): C2SSproto.sync_machine_storm_gold_request {
		return <C2SSproto.sync_machine_storm_gold_request>this.Protocol.GenRequest(this.sync_machine_storm_gold);
	}

	public get sync_user_info_Request(): C2SSproto.sync_user_info_request {
		return <C2SSproto.sync_user_info_request>this.Protocol.GenRequest(this.sync_user_info);
	}

	public get sync_user_info_Response(): C2SSproto.sync_user_info_response {
		return <C2SSproto.sync_user_info_response>this.Protocol.GenResponse(this.sync_user_info);
	}

	public get take_mail_reward_Request(): C2SSproto.take_mail_reward_request {
		return <C2SSproto.take_mail_reward_request>this.Protocol.GenRequest(this.take_mail_reward);
	}

	public get take_mail_reward_Response(): C2SSproto.take_mail_reward_response {
		return <C2SSproto.take_mail_reward_response>this.Protocol.GenResponse(this.take_mail_reward);
	}

	public get unbind_phone_number_Request(): C2SSproto.unbind_phone_number_request {
		return <C2SSproto.unbind_phone_number_request>this.Protocol.GenRequest(this.unbind_phone_number);
	}

	public get unbind_phone_number_Response(): C2SSproto.unbind_phone_number_response {
		return <C2SSproto.unbind_phone_number_response>this.Protocol.GenResponse(this.unbind_phone_number);
	}

	public get update_user_bio_Request(): C2SSproto.update_user_bio_request {
		return <C2SSproto.update_user_bio_request>this.Protocol.GenRequest(this.update_user_bio);
	}

	public get update_user_bio_Response(): C2SSproto.update_user_bio_response {
		return <C2SSproto.update_user_bio_response>this.Protocol.GenResponse(this.update_user_bio);
	}

	public get use_prop_Request(): C2SSproto.use_prop_request {
		return <C2SSproto.use_prop_request>this.Protocol.GenRequest(this.use_prop);
	}

	public get use_prop_Response(): C2SSproto.use_prop_response {
		return <C2SSproto.use_prop_response>this.Protocol.GenResponse(this.use_prop);
	}

	public get use_spec_bullet_Request(): C2SSproto.use_spec_bullet_request {
		return <C2SSproto.use_spec_bullet_request>this.Protocol.GenRequest(this.use_spec_bullet);
	}

	public get use_spec_bullet_Response(): C2SSproto.use_spec_bullet_response {
		return <C2SSproto.use_spec_bullet_response>this.Protocol.GenResponse(this.use_spec_bullet);
	}

	public get user_feedback_Request(): C2SSproto.user_feedback_request {
		return <C2SSproto.user_feedback_request>this.Protocol.GenRequest(this.user_feedback);
	}

	public get user_feedback_Response(): C2SSproto.user_feedback_response {
		return <C2SSproto.user_feedback_response>this.Protocol.GenResponse(this.user_feedback);
	}

	public get verify_phone_number_Request(): C2SSproto.verify_phone_number_request {
		return <C2SSproto.verify_phone_number_request>this.Protocol.GenRequest(this.verify_phone_number);
	}

	public get verify_phone_number_Response(): C2SSproto.verify_phone_number_response {
		return <C2SSproto.verify_phone_number_response>this.Protocol.GenResponse(this.verify_phone_number);
	}

}