// Generated by sprotodump. DO NOT EDIT!
// source: S2C.sproto

namespace S2CSproto { 
	export class accu_rechar_item extends Sp.SprotoTypeBase {
	
		public push_type: number = 0;
		public id: number = 0;
		public recharge_money: number = 0;
		public rewards: Array<prop> = [];
		public summary: string = "";
		public note2: string = "";
		public note3: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.push_type = 0;
			this.id = 0;
			this.recharge_money = 0;
			this.rewards.length = 0;
			this.summary = "";
			this.note2 = "";
			this.note3 = "";
			return this;
		}

	}


	export class accu_rechar_stage extends Sp.SprotoTypeBase {
	
		public stage_info: act_stage_comm = new act_stage_comm();
		public accu_rechar_items: Array<accu_rechar_item> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.stage_info = <act_stage_comm>this.stage_info.reset();
			this.accu_rechar_items.length = 0;
			return this;
		}

	}


	export class act_stage_comm extends Sp.SprotoTypeBase {
	
		public stage: number = 0;
		public pic: string = "";
		public name: string = "";
		public start_time: number = 0;
		public end_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.stage = 0;
			this.pic = "";
			this.name = "";
			this.start_time = 0;
			this.end_time = 0;
			return this;
		}

	}


	export class activity_info extends Sp.SprotoTypeBase {
	
		public guid: number = 0;
		public style: number = 0;
		public main_title: string = "";
		public sub_title: string = "";
		public tag: number = 0;
		public highlight: number = 0;
		public order: number = 0;
		public start_time: number = 0;
		public end_time: number = 0;
		public create_time: number = 0;
		public target_url: string = "";
		public image_src: string = "";
		public content: string = "";
		public readever: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.guid = 0;
			this.style = 0;
			this.main_title = "";
			this.sub_title = "";
			this.tag = 0;
			this.highlight = 0;
			this.order = 0;
			this.start_time = 0;
			this.end_time = 0;
			this.create_time = 0;
			this.target_url = "";
			this.image_src = "";
			this.content = "";
			this.readever = 0;
			return this;
		}

	}


	export class add_speed_bullet_request extends Sp.SprotoTypeBase {
	
		public add_speed: number = 0;
		public time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.add_speed = 0;
			this.time = 0;
			return this;
		}

	}


	export class bought_monthly_card_request extends Sp.SprotoTypeBase {
	
		public end_time: number = 0;
		public given_items: Array<prop> = [];
		public total_diamond: number = 0;
		public total_gold: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.end_time = 0;
			this.given_items.length = 0;
			this.total_diamond = 0;
			this.total_gold = "";
			return this;
		}

	}


	export class broadcast_tips extends Sp.SprotoTypeBase {
	
		public fishid: number = 0;
		public vip: number = 0;
		public nickname: string = "";
		public gold: number = 0;
		public itemid: number = 0;
		public quantity: number = 0;
		public silo_factor: number = 0;
		public gold_factor: number = 0;
		public energy: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.fishid = 0;
			this.vip = 0;
			this.nickname = "";
			this.gold = 0;
			this.itemid = 0;
			this.quantity = 0;
			this.silo_factor = 0;
			this.gold_factor = 0;
			this.energy = 0;
			return this;
		}

	}


	export class bulletin extends Sp.SprotoTypeBase {
	
		public nickname: string = "";
		public avatar: string = "";
		public vip_level: number = 0;
		public multiple: number = 0;
		public highlight: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.nickname = "";
			this.avatar = "";
			this.vip_level = 0;
			this.multiple = 0;
			this.highlight = 0;
			return this;
		}

	}


	export class cannon_power_request extends Sp.SprotoTypeBase {
	
		public power_value: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.power_value = 0;
			return this;
		}

	}


	export class change_cannon_request extends Sp.SprotoTypeBase {
	
		public cannon_id: number = 0;
		public time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.cannon_id = 0;
			this.time = 0;
			return this;
		}

	}


	export class change_num_fish_expert_request extends Sp.SprotoTypeBase {
	
		public fish_num: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.fish_num = 0;
			return this;
		}

	}


	export class change_table_status_request extends Sp.SprotoTypeBase {
	
		public table_status: number = 0;
		public multiple_max: number = 0;
		public multiple_locked: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.table_status = 0;
			this.multiple_max = 0;
			this.multiple_locked = 0;
			return this;
		}

	}


	export class cond extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public quantity: number = 0;
		public para: Array<number> = [];
		public para_range: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.quantity = 0;
			this.para.length = 0;
			this.para_range = 0;
			return this;
		}

	}


	export class daily_share extends Sp.SprotoTypeBase {
	
		public push_type: number = 0;
		public share_num: number = 0;
		public rewards: Array<prop> = [];
		public summary: string = "";
		public interval: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.push_type = 0;
			this.share_num = 0;
			this.rewards.length = 0;
			this.summary = "";
			this.interval = 0;
			return this;
		}

	}


	export class delete_mail_request extends Sp.SprotoTypeBase {
	
		public guids: Array<string> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.guids.length = 0;
			return this;
		}

	}


	export class energy_room_exchange_sync_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public items: Array<prop> = [];
		public energy: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.items.length = 0;
			this.energy = "";
			return this;
		}

	}


	export class equipment extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public create_time: number = 0;
		public expire_time: number = 0;
		public is_use: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.create_time = 0;
			this.expire_time = 0;
			this.is_use = 0;
			return this;
		}

	}


	export class exchange_rcd extends Sp.SprotoTypeBase {
	
		public push_type: number = 0;
		public id: number = 0;
		public name: string = "";
		public consume_item: Array<prop> = [];
		public exchange_item: Array<prop> = [];
		public exchange_count: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.push_type = 0;
			this.id = 0;
			this.name = "";
			this.consume_item.length = 0;
			this.exchange_item.length = 0;
			this.exchange_count = 0;
			return this;
		}

	}


	export class fire_event extends Sp.SprotoTypeBase {
	
		public rot: string = "";
		public bullet_id: number = 0;
		public lock_fish_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rot = "";
			this.bullet_id = 0;
			this.lock_fish_id = 0;
			return this;
		}

	}


	export class fish extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public tag_id: number = 0;
		public path: Array<number> = [];
		public time: number = 0;
		public change_id: number = 0;
		public func_ids: Array<number> = [];
		public func_params: Array<number> = [];
		public pos: number = 0;
		public protect_tag: number = 0;
		public forzen_t: number = 0;
		public expiration_t: number = 0;
		public score: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.tag_id = 0;
			this.path.length = 0;
			this.time = 0;
			this.change_id = 0;
			this.func_ids.length = 0;
			this.func_params.length = 0;
			this.pos = 0;
			this.protect_tag = 0;
			this.forzen_t = 0;
			this.expiration_t = 0;
			this.score = 0;
			return this;
		}

	}


	export class fish_array_coming_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class fish_array_finish_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class fish_change_request extends Sp.SprotoTypeBase {
	
		public tag_id: number = 0;
		public change_id: number = 0;
		public fish: fish = new fish();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.tag_id = 0;
			this.change_id = 0;
			this.fish = <fish>this.fish.reset();
			return this;
		}

	}


	export class fish_net_event extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public fishes: Array<victim> = [];
		public factor: number = 0;
		public silo_award: number = 0;
		public total_gold: string = "";
		public total_exp: number = 0;
		public func_id: number = 0;
		public net_id: number = 0;
		public total_diamond: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.fishes.length = 0;
			this.factor = 0;
			this.silo_award = 0;
			this.total_gold = "";
			this.total_exp = 0;
			this.func_id = 0;
			this.net_id = 0;
			this.total_diamond = 0;
			return this;
		}

	}


	export class fish_run_away_request extends Sp.SprotoTypeBase {
	
		public tags: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.tags.length = 0;
			return this;
		}

	}


	export class func_penetration_conn_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public func_id: number = 0;
		public net_id: number = 0;
		public fishid: number = 0;
		public fish_tag_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.func_id = 0;
			this.net_id = 0;
			this.fishid = 0;
			this.fish_tag_id = 0;
			return this;
		}

	}


	export class function_timer_start_request extends Sp.SprotoTypeBase {
	
		public func_id: number = 0;
		public uid: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.func_id = 0;
			this.uid = "";
			return this;
		}

	}


	export class game_activity_list_request extends Sp.SprotoTypeBase {
	
		public list: Array<activity_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.list.length = 0;
			return this;
		}

	}


	export class game_broadcast_info_request extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public id: number = 0;
		public info: Array<string> = [];
		public str: string = "";
		public tips: broadcast_tips = new broadcast_tips();
		public order: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.id = 0;
			this.info.length = 0;
			this.str = "";
			this.tips = <broadcast_tips>this.tips.reset();
			this.order = 0;
			return this;
		}

	}


	export class gift extends Sp.SprotoTypeBase {
	
		public gid: number = 0;
		public pos: Array<number> = [];
		public pattern: number = 0;
		public cost: number = 0;
		public price: number = 0;
		public title: string = "";
		public expires: number = 0;
		public rewards: Array<prop> = [];
		public original: number = 0;
		public bargain: number = 0;
		public order: number = 0;
		public limit: number = 0;
		public shown: number = 0;
		public title_url: string = "";
		public icon_url: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.gid = 0;
			this.pos.length = 0;
			this.pattern = 0;
			this.cost = 0;
			this.price = 0;
			this.title = "";
			this.expires = 0;
			this.rewards.length = 0;
			this.original = 0;
			this.bargain = 0;
			this.order = 0;
			this.limit = 0;
			this.shown = 0;
			this.title_url = "";
			this.icon_url = "";
			return this;
		}

	}


	export class gift_notice_request extends Sp.SprotoTypeBase {
	
		public list: Array<gift> = [];
		public pos: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.list.length = 0;
			this.pos = 0;
			return this;
		}

	}


	export class goods_info extends Sp.SprotoTypeBase {
	
		public goods_id: number = 0;
		public goods_name: string = "";
		public mall_type: number = 0;
		public item_id: number = 0;
		public quantity: number = 0;
		public recommend: boolean = false;
		public promotion: number = 0;
		public message: string = "";
		public cost: number = 0;
		public price: number = 0;
		public vip: number = 0;
		public goods_icon: string = "";
		public rewards: Array<prop> = [];
		public extra: prop = new prop();
		public goods_description: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.goods_id = 0;
			this.goods_name = "";
			this.mall_type = 0;
			this.item_id = 0;
			this.quantity = 0;
			this.recommend = false;
			this.promotion = 0;
			this.message = "";
			this.cost = 0;
			this.price = 0;
			this.vip = 0;
			this.goods_icon = "";
			this.rewards.length = 0;
			this.extra = <prop>this.extra.reset();
			this.goods_description = "";
			return this;
		}

	}


	export class gos extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public count: number = 0;
		public timeout: number = 0;
		public done: boolean = false;
		public name: string = "";
		public style: number = 0;
		public desc: string = "";
		public order: number = 0;
		public price: number = 0;
		public prime: number = 0;
		public max_timeout: number = 0;
		public premier: Array<prop> = [];
		public repeats: Array<prop> = [];
		public extra: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.count = 0;
			this.timeout = 0;
			this.done = false;
			this.name = "";
			this.style = 0;
			this.desc = "";
			this.order = 0;
			this.price = 0;
			this.prime = 0;
			this.max_timeout = 0;
			this.premier.length = 0;
			this.repeats.length = 0;
			this.extra.length = 0;
			return this;
		}

	}


	export class grow_up_task_info extends Sp.SprotoTypeBase {
	
		public task_id: number = 0;
		public completed_num: number = 0;
		public status: number = 0;
		public day_seq: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.task_id = 0;
			this.completed_num = 0;
			this.status = 0;
			this.day_seq = 0;
			return this;
		}

	}


	export class invite_bind extends Sp.SprotoTypeBase {
	
		public push_type: number = 0;
		public id: number = 0;
		public inv_rewards: Array<prop> = [];
		public inved_rewards: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.push_type = 0;
			this.id = 0;
			this.inv_rewards.length = 0;
			this.inved_rewards.length = 0;
			return this;
		}

	}


	export class invite_task extends Sp.SprotoTypeBase {
	
		public push_type: number = 0;
		public id: number = 0;
		public simple: string = "";
		public simple1: string = "";
		public complete_condition: cond = new cond();
		public rewards: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.push_type = 0;
			this.id = 0;
			this.simple = "";
			this.simple1 = "";
			this.complete_condition = <cond>this.complete_condition.reset();
			this.rewards.length = 0;
			return this;
		}

	}


	export class kick_user_request extends Sp.SprotoTypeBase {
	
		public reason: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.reason = 0;
			return this;
		}

	}


	export class login_queue_wait_request extends Sp.SprotoTypeBase {
	
		public wait_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.wait_time = 0;
			return this;
		}

	}


	export class lucky_purch_cfg_item extends Sp.SprotoTypeBase {
	
		public push_type: number = 0;
		public id: number = 0;
		public stage: number = 0;
		public name: string = "";
		public rewards: Array<prop> = [];
		public req_qty: number = 0;
		public consume_type: number = 0;
		public valid_time: number = 0;
		public show_tab: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.push_type = 0;
			this.id = 0;
			this.stage = 0;
			this.name = "";
			this.rewards.length = 0;
			this.req_qty = 0;
			this.consume_type = 0;
			this.valid_time = 0;
			this.show_tab = 0;
			return this;
		}

	}


	export class lucky_purch_item extends Sp.SprotoTypeBase {
	
		public msg_type: number = 0;
		public id: number = 0;
		public purched_num: number = 0;
		public draw_time: number = 0;
		public status: number = 0;
		public stage: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.msg_type = 0;
			this.id = 0;
			this.purched_num = 0;
			this.draw_time = 0;
			this.status = 0;
			this.stage = 0;
			return this;
		}

	}


	export class machine_storm_request extends Sp.SprotoTypeBase {
	
		public init: boolean = false;
		public silo_id: number = 0;
		public time: number = 0;
		public factor: number = 0;
		public add_time: number = 0;
		public add_factor: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.init = false;
			this.silo_id = 0;
			this.time = 0;
			this.factor = 0;
			this.add_time = 0;
			this.add_factor = 0;
			return this;
		}

	}


	export class mail extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public guid: string = "";
		public type: number = 0;
		public title: string = "";
		public content: string = "";
		public reward: Array<prop> = [];
		public create_time: number = 0;
		public state: number = 0;
		public expire_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.guid = "";
			this.type = 0;
			this.title = "";
			this.content = "";
			this.reward.length = 0;
			this.create_time = 0;
			this.state = 0;
			this.expire_time = 0;
			return this;
		}

	}


	export class mail_list_request extends Sp.SprotoTypeBase {
	
		public mails: Array<mail> = [];
		public is_end: boolean = false;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.mails.length = 0;
			this.is_end = false;
			return this;
		}

	}


	export class mall_list_request extends Sp.SprotoTypeBase {
	
		public list: Array<goods_info> = [];
		public action: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.list.length = 0;
			this.action = 0;
			return this;
		}

	}


	export class new_fish_item extends Sp.SprotoTypeBase {
	
		public push_type: number = 0;
		public id: number = 0;
		public simple: string = "";
		public simple1: string = "";
		public complete_condition: cond = new cond();
		public rewards: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.push_type = 0;
			this.id = 0;
			this.simple = "";
			this.simple1 = "";
			this.complete_condition = <cond>this.complete_condition.reset();
			this.rewards.length = 0;
			return this;
		}

	}


	export class new_fish_stage extends Sp.SprotoTypeBase {
	
		public stage_info: act_stage_comm = new act_stage_comm();
		public new_fish_items: Array<new_fish_item> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.stage_info = <act_stage_comm>this.stage_info.reset();
			this.new_fish_items.length = 0;
			return this;
		}

	}


	export class new_task_info extends Sp.SprotoTypeBase {
	
		public push_type: number = 0;
		public task_id: number = 0;
		public completed_num: number = 0;
		public status: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.push_type = 0;
			this.task_id = 0;
			this.completed_num = 0;
			this.status = 0;
			return this;
		}

	}


	export class notice_request extends Sp.SprotoTypeBase {
	
		public content: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.content = "";
			return this;
		}

	}


	export class notify_gold_fill_request extends Sp.SprotoTypeBase {
	
		public notice: string = "";
		public total_gold: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.notice = "";
			this.total_gold = "";
			return this;
		}

	}


	export class notify_gold_fish_lottery_request extends Sp.SprotoTypeBase {
	
		public score: number = 0;
		public new_level: number = 0;
		public gold_fish_num: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.score = 0;
			this.new_level = 0;
			this.gold_fish_num = 0;
			return this;
		}

	}


	export class package1 extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public session: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.session = 0;
			return this;
		}

	}


	export class pay_order_result_request extends Sp.SprotoTypeBase {
	
		public out_trade_no: string = "";
		public success: boolean = false;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.out_trade_no = "";
			this.success = false;
			return this;
		}

	}


	export class penetration_shoot_sync_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public rot: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.rot = "";
			return this;
		}

	}


	export class popup_msg_request extends Sp.SprotoTypeBase {
	
		public content: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.content = "";
			return this;
		}

	}


	export class prop extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public quantity: number = 0;
		public add_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.quantity = 0;
			this.add_time = 0;
			return this;
		}

	}


	export class purchase_notify_request extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public items: Array<prop> = [];
		public total_gold: string = "";
		public total_diamond: number = 0;
		public mall_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.items.length = 0;
			this.total_gold = "";
			this.total_diamond = 0;
			this.mall_id = 0;
			return this;
		}

	}


	export class push_activity_cfg_request extends Sp.SprotoTypeBase {
	
		public ac_id: number = 0;
		public daily_share_cfg: Array<daily_share> = [];
		public invite_task_cfg: Array<invite_task> = [];
		public exchange_item_cfg: Array<exchange_rcd> = [];
		public invite_bind_cfg: Array<invite_bind> = [];
		public new_fish_expert_cfg: new_fish_stage = new new_fish_stage();
		public accu_recharge_cfg: accu_rechar_stage = new accu_rechar_stage();
		public lucky_purch_cfg: Array<lucky_purch_cfg_item> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.ac_id = 0;
			this.daily_share_cfg.length = 0;
			this.invite_task_cfg.length = 0;
			this.exchange_item_cfg.length = 0;
			this.invite_bind_cfg.length = 0;
			this.new_fish_expert_cfg = <new_fish_stage>this.new_fish_expert_cfg.reset();
			this.accu_recharge_cfg = <accu_rechar_stage>this.accu_recharge_cfg.reset();
			this.lucky_purch_cfg.length = 0;
			return this;
		}

	}


	export class push_bulletins_request extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public action: number = 0;
		public bulletins: Array<bulletin> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.action = 0;
			this.bulletins.length = 0;
			return this;
		}

	}


	export class push_calling_fish_request extends Sp.SprotoTypeBase {
	
		public tag_ids: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.tag_ids.length = 0;
			return this;
		}

	}


	export class push_changed_equipment_request extends Sp.SprotoTypeBase {
	
		public change_type: number = 0;
		public equip_list: Array<equipment> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.change_type = 0;
			this.equip_list.length = 0;
			return this;
		}

	}


	export class push_changed_grow_up_task_request extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public task_list: Array<grow_up_task_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.task_list.length = 0;
			return this;
		}

	}


	export class push_changed_sand_task_request extends Sp.SprotoTypeBase {
	
		public day_seq: number = 0;
		public tasks: Array<task_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.day_seq = 0;
			this.tasks.length = 0;
			return this;
		}

	}


	export class push_changed_task_request extends Sp.SprotoTypeBase {
	
		public list: Array<task_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.list.length = 0;
			return this;
		}

	}


	export class push_clear_activity_request extends Sp.SprotoTypeBase {
	
		public activity_id: number = 0;
		public next_stage: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.activity_id = 0;
			this.next_stage = 0;
			return this;
		}

	}


	export class push_common_activity_request extends Sp.SprotoTypeBase {
	
		public activity_id: number = 0;
		public quantity: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.activity_id = 0;
			this.quantity = 0;
			return this;
		}

	}


	export class push_gift_result_request extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public gid: number = 0;
		public pos: number = 0;
		public total_gold: string = "";
		public total_diamond: number = 0;
		public items: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.gid = 0;
			this.pos = 0;
			this.total_gold = "";
			this.total_diamond = 0;
			this.items.length = 0;
			return this;
		}

	}


	export class push_gos_request extends Sp.SprotoTypeBase {
	
		public action: number = 0;
		public res: Array<gos> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.action = 0;
			this.res.length = 0;
			return this;
		}

	}


	export class push_gos_result_request extends Sp.SprotoTypeBase {
	
		public error_code: number = 0;
		public id: number = 0;
		public total_gold: string = "";
		public total_diamond: string = "";
		public rewards: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.error_code = 0;
			this.id = 0;
			this.total_gold = "";
			this.total_diamond = "";
			this.rewards.length = 0;
			return this;
		}

	}


	export class push_grow_up_activity_request extends Sp.SprotoTypeBase {
	
		public create_time: number = 0;
		public total_score: number = 0;
		public task_list: Array<grow_up_task_info> = [];
		public score_rewarded: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.create_time = 0;
			this.total_score = 0;
			this.task_list.length = 0;
			this.score_rewarded.length = 0;
			return this;
		}

	}


	export class push_liveness_request extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public value: number = 0;
		public rewarded_record: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.value = 0;
			this.rewarded_record.length = 0;
			return this;
		}

	}


	export class push_lucky_purch_request extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.id = 0;
			return this;
		}

	}


	export class push_mul_activity_request extends Sp.SprotoTypeBase {
	
		public ac_id: number = 0;
		public task_list: Array<new_task_info> = [];
		public lucky_purch: Array<lucky_purch_item> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.ac_id = 0;
			this.task_list.length = 0;
			this.lucky_purch.length = 0;
			return this;
		}

	}


	export class push_new_fish_expert_task_request extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public task_list: Array<new_task_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.task_list.length = 0;
			return this;
		}

	}


	export class push_ninja_game_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class push_red_packet_draw_request extends Sp.SprotoTypeBase {
	
		public type: number = 0;
		public cosumed_gold: number = 0;
		public draw_id: number = 0;
		public drawed_count: number = 0;
		public red_packet_value: number = 0;
		public activity_end_time: number = 0;
		public exchanged: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.type = 0;
			this.cosumed_gold = 0;
			this.draw_id = 0;
			this.drawed_count = 0;
			this.red_packet_value = 0;
			this.activity_end_time = 0;
			this.exchanged.length = 0;
			return this;
		}

	}


	export class push_removed_task_request extends Sp.SprotoTypeBase {
	
		public task_ids: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.task_ids.length = 0;
			return this;
		}

	}


	export class push_rookie_process_request extends Sp.SprotoTypeBase {
	
		public value: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.value = 0;
			return this;
		}

	}


	export class push_skill_info_request extends Sp.SprotoTypeBase {
	
		public skill_type: number = 0;
		public time: number = 0;
		public tag_ids: Array<number> = [];
		public cannon_id: number = 0;
		public add_speed: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.skill_type = 0;
			this.time = 0;
			this.tag_ids.length = 0;
			this.cannon_id = 0;
			this.add_speed = 0;
			return this;
		}

	}


	export class push_specific_prop_request extends Sp.SprotoTypeBase {
	
		public props: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.props.length = 0;
			return this;
		}

	}


	export class rank_info extends Sp.SprotoTypeBase {
	
		public account_id: number = 0;
		public score: string = "";
		public rank: number = 0;
		public user_bio: user_bio = new user_bio();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.account_id = 0;
			this.score = "";
			this.rank = 0;
			this.user_bio = <user_bio>this.user_bio.reset();
			return this;
		}

	}


	export class reach_cond extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public num: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.num = 0;
			return this;
		}

	}


	export class room_act_rank_info extends Sp.SprotoTypeBase {
	
		public account_id: number = 0;
		public score: string = "";
		public rank: number = 0;
		public data: Array<prop> = [];
		public user_bio: user_bio = new user_bio();
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.account_id = 0;
			this.score = "";
			this.rank = 0;
			this.data.length = 0;
			this.user_bio = <user_bio>this.user_bio.reset();
			return this;
		}

	}


	export class room_kick_user_request extends Sp.SprotoTypeBase {
	
		public reason: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.reason = 0;
			return this;
		}

	}


	export class s2c_test_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class send_energy_rank_data_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public rank_data: Array<rank_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.rank_data.length = 0;
			return this;
		}

	}


	export class send_energy_rank_data_end_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			return this;
		}

	}


	export class send_energy_rank_data_start_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			return this;
		}

	}


	export class send_last_energy_rank_data_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public rank_data: Array<rank_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.rank_data.length = 0;
			return this;
		}

	}


	export class send_last_energy_rank_data_end_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			return this;
		}

	}


	export class send_last_energy_rank_data_start_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			return this;
		}

	}


	export class send_last_rank_data_request extends Sp.SprotoTypeBase {
	
		public rank_type: number = 0;
		public rank_data: Array<rank_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rank_type = 0;
			this.rank_data.length = 0;
			return this;
		}

	}


	export class send_last_rank_data_end_request extends Sp.SprotoTypeBase {
	
		public rank_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rank_type = 0;
			return this;
		}

	}


	export class send_last_rank_data_start_request extends Sp.SprotoTypeBase {
	
		public rank_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rank_type = 0;
			return this;
		}

	}


	export class send_rank_data_request extends Sp.SprotoTypeBase {
	
		public rank_type: number = 0;
		public rank_data: Array<rank_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rank_type = 0;
			this.rank_data.length = 0;
			return this;
		}

	}


	export class send_rank_data_end_request extends Sp.SprotoTypeBase {
	
		public rank_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rank_type = 0;
			return this;
		}

	}


	export class send_rank_data_start_request extends Sp.SprotoTypeBase {
	
		public rank_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rank_type = 0;
			return this;
		}

	}


	export class send_room_act_rank_data_request extends Sp.SprotoTypeBase {
	
		public rank_data: Array<room_act_rank_info> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.rank_data.length = 0;
			return this;
		}

	}


	export class send_room_act_rank_data_end_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class send_room_act_rank_data_start_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class skill_remain_time_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public skill_time_list: Array<skill_time> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.skill_time_list.length = 0;
			return this;
		}

	}


	export class skill_time extends Sp.SprotoTypeBase {
	
		public skill_id: number = 0;
		public time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.skill_id = 0;
			this.time = 0;
			return this;
		}

	}


	export class small_boss_escape_request extends Sp.SprotoTypeBase {
	
		public tag_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.tag_id = 0;
			return this;
		}

	}


	export class spawn_fish_request extends Sp.SprotoTypeBase {
	
		public fishes: Array<fish> = [];
		public svr_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.fishes.length = 0;
			this.svr_time = 0;
			return this;
		}

	}


	export class spawn_fish_array_request extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public fishes: Array<fish> = [];
		public svr_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.fishes.length = 0;
			this.svr_time = 0;
			return this;
		}

	}


	export class spawn_small_boss_request extends Sp.SprotoTypeBase {
	
		public small_boss: fish = new fish();
		public svr_time: number = 0;
		public end_time: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.small_boss = <fish>this.small_boss.reset();
			this.svr_time = 0;
			this.end_time = 0;
			return this;
		}

	}


	export class spec_bullet_score_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public id: number = 0;
		public gold: number = 0;
		public total_gold: string = "";
		public fishes: Array<victim> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.id = 0;
			this.gold = 0;
			this.total_gold = "";
			this.fishes.length = 0;
			return this;
		}

	}


	export class summon_boss_rewards_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public fishid: number = 0;
		public items: Array<prop> = [];
		public timeout: number = 0;
		public total_score: number = 0;
		public extra: string = "";
		public multiple: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.fishid = 0;
			this.items.length = 0;
			this.timeout = 0;
			this.total_score = 0;
			this.extra = "";
			this.multiple = 0;
			return this;
		}

	}


	export class switch_cannon_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public cannon_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.cannon_id = 0;
			return this;
		}

	}


	export class sync_bankruptcy_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public bankruptcy: boolean = false;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.bankruptcy = false;
			return this;
		}

	}


	export class sync_bomb_fish_click_request extends Sp.SprotoTypeBase {
	
		public tag_id: number = 0;
		public status: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.tag_id = 0;
			this.status = 0;
			return this;
		}

	}


	export class sync_machine_storm_gold_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public gold: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.gold = 0;
			return this;
		}

	}


	export class sync_skill_effect_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public skill_type: number = 0;
		public tag_ids: Array<number> = [];
		public is_first: number = 0;
		public add_speed: number = 0;
		public cannon_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.skill_type = 0;
			this.tag_ids.length = 0;
			this.is_first = 0;
			this.add_speed = 0;
			this.cannon_id = 0;
			return this;
		}

	}


	export class sync_skill_end_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public skill_type: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.skill_type = 0;
			return this;
		}

	}


	export class sync_using_cannon_multiple_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public multiple: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.multiple = 0;
			return this;
		}

	}


	export class sync_vip_info_request extends Sp.SprotoTypeBase {
	
		public vip: number = 0;
		public process: number = 0;
		public maximum: number = 0;
		public promoted: boolean = false;
		public rewards: Array<prop> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.vip = 0;
			this.process = 0;
			this.maximum = 0;
			this.promoted = false;
			this.rewards.length = 0;
			return this;
		}

	}


	export class table_clear_fish_request extends Sp.SprotoTypeBase {
	
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			return this;
		}

	}


	export class table_eat_fish_request extends Sp.SprotoTypeBase {
	
		public eat_id: number = 0;
		public tag_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.eat_id = 0;
			this.tag_id = 0;
			return this;
		}

	}


	export class table_fire_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public rot: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.rot = "";
			return this;
		}

	}


	export class table_fish_net_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public fishes: Array<victim> = [];
		public factor: number = 0;
		public silo_award: number = 0;
		public total_gold: string = "";
		public total_exp: number = 0;
		public func_id: number = 0;
		public net_id: number = 0;
		public total_diamond: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.fishes.length = 0;
			this.factor = 0;
			this.silo_award = 0;
			this.total_gold = "";
			this.total_exp = 0;
			this.func_id = 0;
			this.net_id = 0;
			this.total_diamond = 0;
			return this;
		}

	}


	export class table_player_sit_down_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public chair_id: number = 0;
		public gold: string = "";
		public level: number = 0;
		public gender: number = 0;
		public nickname: string = "";
		public img_url: string = "";
		public diamond: number = 0;
		public unlock_battery: number = 0;
		public using_cannon: number = 0;
		public using_cannon_multiple: number = 0;
		public is_bankruptcy: boolean = false;
		public vip_level: number = 0;
		public items: Array<prop> = [];
		public account_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.chair_id = 0;
			this.gold = "";
			this.level = 0;
			this.gender = 0;
			this.nickname = "";
			this.img_url = "";
			this.diamond = 0;
			this.unlock_battery = 0;
			this.using_cannon = 0;
			this.using_cannon_multiple = 0;
			this.is_bankruptcy = false;
			this.vip_level = 0;
			this.items.length = 0;
			this.account_id = 0;
			return this;
		}

	}


	export class table_player_stand_up_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public chair_id: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.chair_id = 0;
			return this;
		}

	}


	export class table_sync_event_request extends Sp.SprotoTypeBase {
	
		public uid: string = "";
		public fires: Array<fire_event> = [];
		public fish_nets: Array<fish_net_event> = [];
		public interval: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.uid = "";
			this.fires.length = 0;
			this.fish_nets.length = 0;
			this.interval = 0;
			return this;
		}

	}


	export class task_info extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public status: number = 0;
		public cond_list: Array<reach_cond> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.status = 0;
			this.cond_list.length = 0;
			return this;
		}

	}


	export class user_bio extends Sp.SprotoTypeBase {
	
		public account_id: number = 0;
		public nickname: string = "";
		public img_url: string = "";
		public gender: number = 0;
		public gold: string = "";
		public diamond: number = 0;
		public level: number = 0;
		public vip: number = 0;
		public signature: string = "";
		public cannon_multiple: number = 0;
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.account_id = 0;
			this.nickname = "";
			this.img_url = "";
			this.gender = 0;
			this.gold = "";
			this.diamond = 0;
			this.level = 0;
			this.vip = 0;
			this.signature = "";
			this.cannon_multiple = 0;
			return this;
		}

	}


	export class user_level_up_request extends Sp.SprotoTypeBase {
	
		public level: number = 0;
		public rewards: Array<prop> = [];
		public total_diamond: number = 0;
		public total_gold: string = "";
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.level = 0;
			this.rewards.length = 0;
			this.total_diamond = 0;
			this.total_gold = "";
			return this;
		}

	}


	export class victim extends Sp.SprotoTypeBase {
	
		public id: number = 0;
		public tag_id: number = 0;
		public score: number = 0;
		public items: Array<prop> = [];
		public func_id: number = 0;
		public net_id: number = 0;
		public factor_list: Array<number> = [];
	
		public constructor () {
			super();
		}

		public reset (): Sp.SprotoTypeBase {
			this.id = 0;
			this.tag_id = 0;
			this.score = 0;
			this.items.length = 0;
			this.func_id = 0;
			this.net_id = 0;
			this.factor_list.length = 0;
			return this;
		}

	}


}

