// Generated by sprotodump. DO NOT EDIT!
class S2CProtocol extends Sp.ProtocolBase {
	public readonly add_speed_bullet: number = 50;
	public readonly bought_monthly_card: number = 49;
	public readonly cannon_power: number = 33;
	public readonly change_cannon: number = 31;
	public readonly change_num_fish_expert: number = 51;
	public readonly change_table_status: number = 84;
	public readonly delete_mail: number = 90;
	public readonly energy_room_exchange_sync: number = 66;
	public readonly fish_array_coming: number = 15;
	public readonly fish_array_finish: number = 27;
	public readonly fish_change: number = 12;
	public readonly fish_run_away: number = 61;
	public readonly func_penetration_conn: number = 55;
	public readonly function_timer_start: number = 41;
	public readonly game_activity_list: number = 36;
	public readonly game_broadcast_info: number = 35;
	public readonly gift_notice: number = 38;
	public readonly heartbeat: number = 1;
	public readonly kick_user: number = 9;
	public readonly login_queue_wait: number = 11;
	public readonly machine_storm: number = 17;
	public readonly mail_list: number = 18;
	public readonly mall_list: number = 34;
	public readonly notice: number = 28;
	public readonly notify_gold_fill: number = 53;
	public readonly notify_gold_fish_lottery: number = 16;
	public readonly pay_order_result: number = 71;
	public readonly penetration_shoot_sync: number = 54;
	public readonly popup_msg: number = 89;
	public readonly purchase_notify: number = 45;
	public readonly push_activity_cfg: number = 83;
	public readonly push_bulletins: number = 92;
	public readonly push_calling_fish: number = 29;
	public readonly push_changed_equipment: number = 58;
	public readonly push_changed_grow_up_task: number = 62;
	public readonly push_changed_sand_task: number = 37;
	public readonly push_changed_task: number = 5;
	public readonly push_clear_activity: number = 72;
	public readonly push_common_activity: number = 59;
	public readonly push_gift_result: number = 57;
	public readonly push_gos: number = 93;
	public readonly push_gos_result: number = 94;
	public readonly push_grow_up_activity: number = 68;
	public readonly push_liveness: number = 10;
	public readonly push_lucky_purch: number = 91;
	public readonly push_mul_activity: number = 86;
	public readonly push_new_fish_expert_task: number = 73;
	public readonly push_ninja_game: number = 60;
	public readonly push_red_packet_draw: number = 67;
	public readonly push_removed_task: number = 70;
	public readonly push_rookie_process: number = 39;
	public readonly push_skill_info: number = 56;
	public readonly push_specific_prop: number = 69;
	public readonly room_kick_user: number = 88;
	public readonly s2c_test: number = 2;
	public readonly send_energy_rank_data: number = 78;
	public readonly send_energy_rank_data_end: number = 79;
	public readonly send_energy_rank_data_start: number = 77;
	public readonly send_last_energy_rank_data: number = 81;
	public readonly send_last_energy_rank_data_end: number = 82;
	public readonly send_last_energy_rank_data_start: number = 80;
	public readonly send_last_rank_data: number = 64;
	public readonly send_last_rank_data_end: number = 65;
	public readonly send_last_rank_data_start: number = 63;
	public readonly send_rank_data: number = 47;
	public readonly send_rank_data_end: number = 48;
	public readonly send_rank_data_start: number = 46;
	public readonly send_room_act_rank_data: number = 75;
	public readonly send_room_act_rank_data_end: number = 76;
	public readonly send_room_act_rank_data_start: number = 74;
	public readonly skill_remain_time: number = 40;
	public readonly small_boss_escape: number = 23;
	public readonly spawn_fish: number = 6;
	public readonly spawn_fish_array: number = 14;
	public readonly spawn_small_boss: number = 22;
	public readonly spec_bullet_score: number = 32;
	public readonly summon_boss_rewards: number = 87;
	public readonly switch_cannon: number = 30;
	public readonly sync_bankruptcy: number = 44;
	public readonly sync_bomb_fish_click: number = 42;
	public readonly sync_machine_storm_gold: number = 43;
	public readonly sync_skill_effect: number = 24;
	public readonly sync_skill_end: number = 25;
	public readonly sync_using_cannon_multiple: number = 21;
	public readonly sync_vip_info: number = 52;
	public readonly table_clear_fish: number = 85;
	public readonly table_eat_fish: number = 26;
	public readonly table_fire: number = 7;
	public readonly table_fish_net: number = 8;
	public readonly table_player_sit_down: number = 3;
	public readonly table_player_stand_up: number = 4;
	public readonly table_sync_event: number = 19;
	public readonly user_level_up: number = 13;

	public constructor() {
		super()
	
		this.Protocol.SetProtocol(this.add_speed_bullet);
		this.Protocol.SetRequest(this.add_speed_bullet ,S2CSproto.add_speed_bullet_request);

		this.Protocol.SetProtocol(this.bought_monthly_card);
		this.Protocol.SetRequest(this.bought_monthly_card ,S2CSproto.bought_monthly_card_request);

		this.Protocol.SetProtocol(this.cannon_power);
		this.Protocol.SetRequest(this.cannon_power ,S2CSproto.cannon_power_request);

		this.Protocol.SetProtocol(this.change_cannon);
		this.Protocol.SetRequest(this.change_cannon ,S2CSproto.change_cannon_request);

		this.Protocol.SetProtocol(this.change_num_fish_expert);
		this.Protocol.SetRequest(this.change_num_fish_expert ,S2CSproto.change_num_fish_expert_request);

		this.Protocol.SetProtocol(this.change_table_status);
		this.Protocol.SetRequest(this.change_table_status ,S2CSproto.change_table_status_request);

		this.Protocol.SetProtocol(this.delete_mail);
		this.Protocol.SetRequest(this.delete_mail ,S2CSproto.delete_mail_request);

		this.Protocol.SetProtocol(this.energy_room_exchange_sync);
		this.Protocol.SetRequest(this.energy_room_exchange_sync ,S2CSproto.energy_room_exchange_sync_request);

		this.Protocol.SetProtocol(this.fish_array_coming);
		this.Protocol.SetRequest(this.fish_array_coming ,S2CSproto.fish_array_coming_request);

		this.Protocol.SetProtocol(this.fish_array_finish);
		this.Protocol.SetRequest(this.fish_array_finish ,S2CSproto.fish_array_finish_request);

		this.Protocol.SetProtocol(this.fish_change);
		this.Protocol.SetRequest(this.fish_change ,S2CSproto.fish_change_request);

		this.Protocol.SetProtocol(this.fish_run_away);
		this.Protocol.SetRequest(this.fish_run_away ,S2CSproto.fish_run_away_request);

		this.Protocol.SetProtocol(this.func_penetration_conn);
		this.Protocol.SetRequest(this.func_penetration_conn ,S2CSproto.func_penetration_conn_request);

		this.Protocol.SetProtocol(this.function_timer_start);
		this.Protocol.SetRequest(this.function_timer_start ,S2CSproto.function_timer_start_request);

		this.Protocol.SetProtocol(this.game_activity_list);
		this.Protocol.SetRequest(this.game_activity_list ,S2CSproto.game_activity_list_request);

		this.Protocol.SetProtocol(this.game_broadcast_info);
		this.Protocol.SetRequest(this.game_broadcast_info ,S2CSproto.game_broadcast_info_request);

		this.Protocol.SetProtocol(this.gift_notice);
		this.Protocol.SetRequest(this.gift_notice ,S2CSproto.gift_notice_request);

		this.Protocol.SetProtocol(this.heartbeat);

		this.Protocol.SetProtocol(this.kick_user);
		this.Protocol.SetRequest(this.kick_user ,S2CSproto.kick_user_request);

		this.Protocol.SetProtocol(this.login_queue_wait);
		this.Protocol.SetRequest(this.login_queue_wait ,S2CSproto.login_queue_wait_request);

		this.Protocol.SetProtocol(this.machine_storm);
		this.Protocol.SetRequest(this.machine_storm ,S2CSproto.machine_storm_request);

		this.Protocol.SetProtocol(this.mail_list);
		this.Protocol.SetRequest(this.mail_list ,S2CSproto.mail_list_request);

		this.Protocol.SetProtocol(this.mall_list);
		this.Protocol.SetRequest(this.mall_list ,S2CSproto.mall_list_request);

		this.Protocol.SetProtocol(this.notice);
		this.Protocol.SetRequest(this.notice ,S2CSproto.notice_request);

		this.Protocol.SetProtocol(this.notify_gold_fill);
		this.Protocol.SetRequest(this.notify_gold_fill ,S2CSproto.notify_gold_fill_request);

		this.Protocol.SetProtocol(this.notify_gold_fish_lottery);
		this.Protocol.SetRequest(this.notify_gold_fish_lottery ,S2CSproto.notify_gold_fish_lottery_request);

		this.Protocol.SetProtocol(this.pay_order_result);
		this.Protocol.SetRequest(this.pay_order_result ,S2CSproto.pay_order_result_request);

		this.Protocol.SetProtocol(this.penetration_shoot_sync);
		this.Protocol.SetRequest(this.penetration_shoot_sync ,S2CSproto.penetration_shoot_sync_request);

		this.Protocol.SetProtocol(this.popup_msg);
		this.Protocol.SetRequest(this.popup_msg ,S2CSproto.popup_msg_request);

		this.Protocol.SetProtocol(this.purchase_notify);
		this.Protocol.SetRequest(this.purchase_notify ,S2CSproto.purchase_notify_request);

		this.Protocol.SetProtocol(this.push_activity_cfg);
		this.Protocol.SetRequest(this.push_activity_cfg ,S2CSproto.push_activity_cfg_request);

		this.Protocol.SetProtocol(this.push_bulletins);
		this.Protocol.SetRequest(this.push_bulletins ,S2CSproto.push_bulletins_request);

		this.Protocol.SetProtocol(this.push_calling_fish);
		this.Protocol.SetRequest(this.push_calling_fish ,S2CSproto.push_calling_fish_request);

		this.Protocol.SetProtocol(this.push_changed_equipment);
		this.Protocol.SetRequest(this.push_changed_equipment ,S2CSproto.push_changed_equipment_request);

		this.Protocol.SetProtocol(this.push_changed_grow_up_task);
		this.Protocol.SetRequest(this.push_changed_grow_up_task ,S2CSproto.push_changed_grow_up_task_request);

		this.Protocol.SetProtocol(this.push_changed_sand_task);
		this.Protocol.SetRequest(this.push_changed_sand_task ,S2CSproto.push_changed_sand_task_request);

		this.Protocol.SetProtocol(this.push_changed_task);
		this.Protocol.SetRequest(this.push_changed_task ,S2CSproto.push_changed_task_request);

		this.Protocol.SetProtocol(this.push_clear_activity);
		this.Protocol.SetRequest(this.push_clear_activity ,S2CSproto.push_clear_activity_request);

		this.Protocol.SetProtocol(this.push_common_activity);
		this.Protocol.SetRequest(this.push_common_activity ,S2CSproto.push_common_activity_request);

		this.Protocol.SetProtocol(this.push_gift_result);
		this.Protocol.SetRequest(this.push_gift_result ,S2CSproto.push_gift_result_request);

		this.Protocol.SetProtocol(this.push_gos);
		this.Protocol.SetRequest(this.push_gos ,S2CSproto.push_gos_request);

		this.Protocol.SetProtocol(this.push_gos_result);
		this.Protocol.SetRequest(this.push_gos_result ,S2CSproto.push_gos_result_request);

		this.Protocol.SetProtocol(this.push_grow_up_activity);
		this.Protocol.SetRequest(this.push_grow_up_activity ,S2CSproto.push_grow_up_activity_request);

		this.Protocol.SetProtocol(this.push_liveness);
		this.Protocol.SetRequest(this.push_liveness ,S2CSproto.push_liveness_request);

		this.Protocol.SetProtocol(this.push_lucky_purch);
		this.Protocol.SetRequest(this.push_lucky_purch ,S2CSproto.push_lucky_purch_request);

		this.Protocol.SetProtocol(this.push_mul_activity);
		this.Protocol.SetRequest(this.push_mul_activity ,S2CSproto.push_mul_activity_request);

		this.Protocol.SetProtocol(this.push_new_fish_expert_task);
		this.Protocol.SetRequest(this.push_new_fish_expert_task ,S2CSproto.push_new_fish_expert_task_request);

		this.Protocol.SetProtocol(this.push_ninja_game);
		this.Protocol.SetRequest(this.push_ninja_game ,S2CSproto.push_ninja_game_request);

		this.Protocol.SetProtocol(this.push_red_packet_draw);
		this.Protocol.SetRequest(this.push_red_packet_draw ,S2CSproto.push_red_packet_draw_request);

		this.Protocol.SetProtocol(this.push_removed_task);
		this.Protocol.SetRequest(this.push_removed_task ,S2CSproto.push_removed_task_request);

		this.Protocol.SetProtocol(this.push_rookie_process);
		this.Protocol.SetRequest(this.push_rookie_process ,S2CSproto.push_rookie_process_request);

		this.Protocol.SetProtocol(this.push_skill_info);
		this.Protocol.SetRequest(this.push_skill_info ,S2CSproto.push_skill_info_request);

		this.Protocol.SetProtocol(this.push_specific_prop);
		this.Protocol.SetRequest(this.push_specific_prop ,S2CSproto.push_specific_prop_request);

		this.Protocol.SetProtocol(this.room_kick_user);
		this.Protocol.SetRequest(this.room_kick_user ,S2CSproto.room_kick_user_request);

		this.Protocol.SetProtocol(this.s2c_test);
		this.Protocol.SetRequest(this.s2c_test ,S2CSproto.s2c_test_request);

		this.Protocol.SetProtocol(this.send_energy_rank_data);
		this.Protocol.SetRequest(this.send_energy_rank_data ,S2CSproto.send_energy_rank_data_request);

		this.Protocol.SetProtocol(this.send_energy_rank_data_end);
		this.Protocol.SetRequest(this.send_energy_rank_data_end ,S2CSproto.send_energy_rank_data_end_request);

		this.Protocol.SetProtocol(this.send_energy_rank_data_start);
		this.Protocol.SetRequest(this.send_energy_rank_data_start ,S2CSproto.send_energy_rank_data_start_request);

		this.Protocol.SetProtocol(this.send_last_energy_rank_data);
		this.Protocol.SetRequest(this.send_last_energy_rank_data ,S2CSproto.send_last_energy_rank_data_request);

		this.Protocol.SetProtocol(this.send_last_energy_rank_data_end);
		this.Protocol.SetRequest(this.send_last_energy_rank_data_end ,S2CSproto.send_last_energy_rank_data_end_request);

		this.Protocol.SetProtocol(this.send_last_energy_rank_data_start);
		this.Protocol.SetRequest(this.send_last_energy_rank_data_start ,S2CSproto.send_last_energy_rank_data_start_request);

		this.Protocol.SetProtocol(this.send_last_rank_data);
		this.Protocol.SetRequest(this.send_last_rank_data ,S2CSproto.send_last_rank_data_request);

		this.Protocol.SetProtocol(this.send_last_rank_data_end);
		this.Protocol.SetRequest(this.send_last_rank_data_end ,S2CSproto.send_last_rank_data_end_request);

		this.Protocol.SetProtocol(this.send_last_rank_data_start);
		this.Protocol.SetRequest(this.send_last_rank_data_start ,S2CSproto.send_last_rank_data_start_request);

		this.Protocol.SetProtocol(this.send_rank_data);
		this.Protocol.SetRequest(this.send_rank_data ,S2CSproto.send_rank_data_request);

		this.Protocol.SetProtocol(this.send_rank_data_end);
		this.Protocol.SetRequest(this.send_rank_data_end ,S2CSproto.send_rank_data_end_request);

		this.Protocol.SetProtocol(this.send_rank_data_start);
		this.Protocol.SetRequest(this.send_rank_data_start ,S2CSproto.send_rank_data_start_request);

		this.Protocol.SetProtocol(this.send_room_act_rank_data);
		this.Protocol.SetRequest(this.send_room_act_rank_data ,S2CSproto.send_room_act_rank_data_request);

		this.Protocol.SetProtocol(this.send_room_act_rank_data_end);
		this.Protocol.SetRequest(this.send_room_act_rank_data_end ,S2CSproto.send_room_act_rank_data_end_request);

		this.Protocol.SetProtocol(this.send_room_act_rank_data_start);
		this.Protocol.SetRequest(this.send_room_act_rank_data_start ,S2CSproto.send_room_act_rank_data_start_request);

		this.Protocol.SetProtocol(this.skill_remain_time);
		this.Protocol.SetRequest(this.skill_remain_time ,S2CSproto.skill_remain_time_request);

		this.Protocol.SetProtocol(this.small_boss_escape);
		this.Protocol.SetRequest(this.small_boss_escape ,S2CSproto.small_boss_escape_request);

		this.Protocol.SetProtocol(this.spawn_fish);
		this.Protocol.SetRequest(this.spawn_fish ,S2CSproto.spawn_fish_request);

		this.Protocol.SetProtocol(this.spawn_fish_array);
		this.Protocol.SetRequest(this.spawn_fish_array ,S2CSproto.spawn_fish_array_request);

		this.Protocol.SetProtocol(this.spawn_small_boss);
		this.Protocol.SetRequest(this.spawn_small_boss ,S2CSproto.spawn_small_boss_request);

		this.Protocol.SetProtocol(this.spec_bullet_score);
		this.Protocol.SetRequest(this.spec_bullet_score ,S2CSproto.spec_bullet_score_request);

		this.Protocol.SetProtocol(this.summon_boss_rewards);
		this.Protocol.SetRequest(this.summon_boss_rewards ,S2CSproto.summon_boss_rewards_request);

		this.Protocol.SetProtocol(this.switch_cannon);
		this.Protocol.SetRequest(this.switch_cannon ,S2CSproto.switch_cannon_request);

		this.Protocol.SetProtocol(this.sync_bankruptcy);
		this.Protocol.SetRequest(this.sync_bankruptcy ,S2CSproto.sync_bankruptcy_request);

		this.Protocol.SetProtocol(this.sync_bomb_fish_click);
		this.Protocol.SetRequest(this.sync_bomb_fish_click ,S2CSproto.sync_bomb_fish_click_request);

		this.Protocol.SetProtocol(this.sync_machine_storm_gold);
		this.Protocol.SetRequest(this.sync_machine_storm_gold ,S2CSproto.sync_machine_storm_gold_request);

		this.Protocol.SetProtocol(this.sync_skill_effect);
		this.Protocol.SetRequest(this.sync_skill_effect ,S2CSproto.sync_skill_effect_request);

		this.Protocol.SetProtocol(this.sync_skill_end);
		this.Protocol.SetRequest(this.sync_skill_end ,S2CSproto.sync_skill_end_request);

		this.Protocol.SetProtocol(this.sync_using_cannon_multiple);
		this.Protocol.SetRequest(this.sync_using_cannon_multiple ,S2CSproto.sync_using_cannon_multiple_request);

		this.Protocol.SetProtocol(this.sync_vip_info);
		this.Protocol.SetRequest(this.sync_vip_info ,S2CSproto.sync_vip_info_request);

		this.Protocol.SetProtocol(this.table_clear_fish);
		this.Protocol.SetRequest(this.table_clear_fish ,S2CSproto.table_clear_fish_request);

		this.Protocol.SetProtocol(this.table_eat_fish);
		this.Protocol.SetRequest(this.table_eat_fish ,S2CSproto.table_eat_fish_request);

		this.Protocol.SetProtocol(this.table_fire);
		this.Protocol.SetRequest(this.table_fire ,S2CSproto.table_fire_request);

		this.Protocol.SetProtocol(this.table_fish_net);
		this.Protocol.SetRequest(this.table_fish_net ,S2CSproto.table_fish_net_request);

		this.Protocol.SetProtocol(this.table_player_sit_down);
		this.Protocol.SetRequest(this.table_player_sit_down ,S2CSproto.table_player_sit_down_request);

		this.Protocol.SetProtocol(this.table_player_stand_up);
		this.Protocol.SetRequest(this.table_player_stand_up ,S2CSproto.table_player_stand_up_request);

		this.Protocol.SetProtocol(this.table_sync_event);
		this.Protocol.SetRequest(this.table_sync_event ,S2CSproto.table_sync_event_request);

		this.Protocol.SetProtocol(this.user_level_up);
		this.Protocol.SetRequest(this.user_level_up ,S2CSproto.user_level_up_request);

	}

	public get add_speed_bullet_Request(): S2CSproto.add_speed_bullet_request {
		return <S2CSproto.add_speed_bullet_request>this.Protocol.GenRequest(this.add_speed_bullet);
	}

	public get bought_monthly_card_Request(): S2CSproto.bought_monthly_card_request {
		return <S2CSproto.bought_monthly_card_request>this.Protocol.GenRequest(this.bought_monthly_card);
	}

	public get cannon_power_Request(): S2CSproto.cannon_power_request {
		return <S2CSproto.cannon_power_request>this.Protocol.GenRequest(this.cannon_power);
	}

	public get change_cannon_Request(): S2CSproto.change_cannon_request {
		return <S2CSproto.change_cannon_request>this.Protocol.GenRequest(this.change_cannon);
	}

	public get change_num_fish_expert_Request(): S2CSproto.change_num_fish_expert_request {
		return <S2CSproto.change_num_fish_expert_request>this.Protocol.GenRequest(this.change_num_fish_expert);
	}

	public get change_table_status_Request(): S2CSproto.change_table_status_request {
		return <S2CSproto.change_table_status_request>this.Protocol.GenRequest(this.change_table_status);
	}

	public get delete_mail_Request(): S2CSproto.delete_mail_request {
		return <S2CSproto.delete_mail_request>this.Protocol.GenRequest(this.delete_mail);
	}

	public get energy_room_exchange_sync_Request(): S2CSproto.energy_room_exchange_sync_request {
		return <S2CSproto.energy_room_exchange_sync_request>this.Protocol.GenRequest(this.energy_room_exchange_sync);
	}

	public get fish_array_coming_Request(): S2CSproto.fish_array_coming_request {
		return <S2CSproto.fish_array_coming_request>this.Protocol.GenRequest(this.fish_array_coming);
	}

	public get fish_array_finish_Request(): S2CSproto.fish_array_finish_request {
		return <S2CSproto.fish_array_finish_request>this.Protocol.GenRequest(this.fish_array_finish);
	}

	public get fish_change_Request(): S2CSproto.fish_change_request {
		return <S2CSproto.fish_change_request>this.Protocol.GenRequest(this.fish_change);
	}

	public get fish_run_away_Request(): S2CSproto.fish_run_away_request {
		return <S2CSproto.fish_run_away_request>this.Protocol.GenRequest(this.fish_run_away);
	}

	public get func_penetration_conn_Request(): S2CSproto.func_penetration_conn_request {
		return <S2CSproto.func_penetration_conn_request>this.Protocol.GenRequest(this.func_penetration_conn);
	}

	public get function_timer_start_Request(): S2CSproto.function_timer_start_request {
		return <S2CSproto.function_timer_start_request>this.Protocol.GenRequest(this.function_timer_start);
	}

	public get game_activity_list_Request(): S2CSproto.game_activity_list_request {
		return <S2CSproto.game_activity_list_request>this.Protocol.GenRequest(this.game_activity_list);
	}

	public get game_broadcast_info_Request(): S2CSproto.game_broadcast_info_request {
		return <S2CSproto.game_broadcast_info_request>this.Protocol.GenRequest(this.game_broadcast_info);
	}

	public get gift_notice_Request(): S2CSproto.gift_notice_request {
		return <S2CSproto.gift_notice_request>this.Protocol.GenRequest(this.gift_notice);
	}

	public get kick_user_Request(): S2CSproto.kick_user_request {
		return <S2CSproto.kick_user_request>this.Protocol.GenRequest(this.kick_user);
	}

	public get login_queue_wait_Request(): S2CSproto.login_queue_wait_request {
		return <S2CSproto.login_queue_wait_request>this.Protocol.GenRequest(this.login_queue_wait);
	}

	public get machine_storm_Request(): S2CSproto.machine_storm_request {
		return <S2CSproto.machine_storm_request>this.Protocol.GenRequest(this.machine_storm);
	}

	public get mail_list_Request(): S2CSproto.mail_list_request {
		return <S2CSproto.mail_list_request>this.Protocol.GenRequest(this.mail_list);
	}

	public get mall_list_Request(): S2CSproto.mall_list_request {
		return <S2CSproto.mall_list_request>this.Protocol.GenRequest(this.mall_list);
	}

	public get notice_Request(): S2CSproto.notice_request {
		return <S2CSproto.notice_request>this.Protocol.GenRequest(this.notice);
	}

	public get notify_gold_fill_Request(): S2CSproto.notify_gold_fill_request {
		return <S2CSproto.notify_gold_fill_request>this.Protocol.GenRequest(this.notify_gold_fill);
	}

	public get notify_gold_fish_lottery_Request(): S2CSproto.notify_gold_fish_lottery_request {
		return <S2CSproto.notify_gold_fish_lottery_request>this.Protocol.GenRequest(this.notify_gold_fish_lottery);
	}

	public get pay_order_result_Request(): S2CSproto.pay_order_result_request {
		return <S2CSproto.pay_order_result_request>this.Protocol.GenRequest(this.pay_order_result);
	}

	public get penetration_shoot_sync_Request(): S2CSproto.penetration_shoot_sync_request {
		return <S2CSproto.penetration_shoot_sync_request>this.Protocol.GenRequest(this.penetration_shoot_sync);
	}

	public get popup_msg_Request(): S2CSproto.popup_msg_request {
		return <S2CSproto.popup_msg_request>this.Protocol.GenRequest(this.popup_msg);
	}

	public get purchase_notify_Request(): S2CSproto.purchase_notify_request {
		return <S2CSproto.purchase_notify_request>this.Protocol.GenRequest(this.purchase_notify);
	}

	public get push_activity_cfg_Request(): S2CSproto.push_activity_cfg_request {
		return <S2CSproto.push_activity_cfg_request>this.Protocol.GenRequest(this.push_activity_cfg);
	}

	public get push_bulletins_Request(): S2CSproto.push_bulletins_request {
		return <S2CSproto.push_bulletins_request>this.Protocol.GenRequest(this.push_bulletins);
	}

	public get push_calling_fish_Request(): S2CSproto.push_calling_fish_request {
		return <S2CSproto.push_calling_fish_request>this.Protocol.GenRequest(this.push_calling_fish);
	}

	public get push_changed_equipment_Request(): S2CSproto.push_changed_equipment_request {
		return <S2CSproto.push_changed_equipment_request>this.Protocol.GenRequest(this.push_changed_equipment);
	}

	public get push_changed_grow_up_task_Request(): S2CSproto.push_changed_grow_up_task_request {
		return <S2CSproto.push_changed_grow_up_task_request>this.Protocol.GenRequest(this.push_changed_grow_up_task);
	}

	public get push_changed_sand_task_Request(): S2CSproto.push_changed_sand_task_request {
		return <S2CSproto.push_changed_sand_task_request>this.Protocol.GenRequest(this.push_changed_sand_task);
	}

	public get push_changed_task_Request(): S2CSproto.push_changed_task_request {
		return <S2CSproto.push_changed_task_request>this.Protocol.GenRequest(this.push_changed_task);
	}

	public get push_clear_activity_Request(): S2CSproto.push_clear_activity_request {
		return <S2CSproto.push_clear_activity_request>this.Protocol.GenRequest(this.push_clear_activity);
	}

	public get push_common_activity_Request(): S2CSproto.push_common_activity_request {
		return <S2CSproto.push_common_activity_request>this.Protocol.GenRequest(this.push_common_activity);
	}

	public get push_gift_result_Request(): S2CSproto.push_gift_result_request {
		return <S2CSproto.push_gift_result_request>this.Protocol.GenRequest(this.push_gift_result);
	}

	public get push_gos_Request(): S2CSproto.push_gos_request {
		return <S2CSproto.push_gos_request>this.Protocol.GenRequest(this.push_gos);
	}

	public get push_gos_result_Request(): S2CSproto.push_gos_result_request {
		return <S2CSproto.push_gos_result_request>this.Protocol.GenRequest(this.push_gos_result);
	}

	public get push_grow_up_activity_Request(): S2CSproto.push_grow_up_activity_request {
		return <S2CSproto.push_grow_up_activity_request>this.Protocol.GenRequest(this.push_grow_up_activity);
	}

	public get push_liveness_Request(): S2CSproto.push_liveness_request {
		return <S2CSproto.push_liveness_request>this.Protocol.GenRequest(this.push_liveness);
	}

	public get push_lucky_purch_Request(): S2CSproto.push_lucky_purch_request {
		return <S2CSproto.push_lucky_purch_request>this.Protocol.GenRequest(this.push_lucky_purch);
	}

	public get push_mul_activity_Request(): S2CSproto.push_mul_activity_request {
		return <S2CSproto.push_mul_activity_request>this.Protocol.GenRequest(this.push_mul_activity);
	}

	public get push_new_fish_expert_task_Request(): S2CSproto.push_new_fish_expert_task_request {
		return <S2CSproto.push_new_fish_expert_task_request>this.Protocol.GenRequest(this.push_new_fish_expert_task);
	}

	public get push_ninja_game_Request(): S2CSproto.push_ninja_game_request {
		return <S2CSproto.push_ninja_game_request>this.Protocol.GenRequest(this.push_ninja_game);
	}

	public get push_red_packet_draw_Request(): S2CSproto.push_red_packet_draw_request {
		return <S2CSproto.push_red_packet_draw_request>this.Protocol.GenRequest(this.push_red_packet_draw);
	}

	public get push_removed_task_Request(): S2CSproto.push_removed_task_request {
		return <S2CSproto.push_removed_task_request>this.Protocol.GenRequest(this.push_removed_task);
	}

	public get push_rookie_process_Request(): S2CSproto.push_rookie_process_request {
		return <S2CSproto.push_rookie_process_request>this.Protocol.GenRequest(this.push_rookie_process);
	}

	public get push_skill_info_Request(): S2CSproto.push_skill_info_request {
		return <S2CSproto.push_skill_info_request>this.Protocol.GenRequest(this.push_skill_info);
	}

	public get push_specific_prop_Request(): S2CSproto.push_specific_prop_request {
		return <S2CSproto.push_specific_prop_request>this.Protocol.GenRequest(this.push_specific_prop);
	}

	public get room_kick_user_Request(): S2CSproto.room_kick_user_request {
		return <S2CSproto.room_kick_user_request>this.Protocol.GenRequest(this.room_kick_user);
	}

	public get s2c_test_Request(): S2CSproto.s2c_test_request {
		return <S2CSproto.s2c_test_request>this.Protocol.GenRequest(this.s2c_test);
	}

	public get send_energy_rank_data_Request(): S2CSproto.send_energy_rank_data_request {
		return <S2CSproto.send_energy_rank_data_request>this.Protocol.GenRequest(this.send_energy_rank_data);
	}

	public get send_energy_rank_data_end_Request(): S2CSproto.send_energy_rank_data_end_request {
		return <S2CSproto.send_energy_rank_data_end_request>this.Protocol.GenRequest(this.send_energy_rank_data_end);
	}

	public get send_energy_rank_data_start_Request(): S2CSproto.send_energy_rank_data_start_request {
		return <S2CSproto.send_energy_rank_data_start_request>this.Protocol.GenRequest(this.send_energy_rank_data_start);
	}

	public get send_last_energy_rank_data_Request(): S2CSproto.send_last_energy_rank_data_request {
		return <S2CSproto.send_last_energy_rank_data_request>this.Protocol.GenRequest(this.send_last_energy_rank_data);
	}

	public get send_last_energy_rank_data_end_Request(): S2CSproto.send_last_energy_rank_data_end_request {
		return <S2CSproto.send_last_energy_rank_data_end_request>this.Protocol.GenRequest(this.send_last_energy_rank_data_end);
	}

	public get send_last_energy_rank_data_start_Request(): S2CSproto.send_last_energy_rank_data_start_request {
		return <S2CSproto.send_last_energy_rank_data_start_request>this.Protocol.GenRequest(this.send_last_energy_rank_data_start);
	}

	public get send_last_rank_data_Request(): S2CSproto.send_last_rank_data_request {
		return <S2CSproto.send_last_rank_data_request>this.Protocol.GenRequest(this.send_last_rank_data);
	}

	public get send_last_rank_data_end_Request(): S2CSproto.send_last_rank_data_end_request {
		return <S2CSproto.send_last_rank_data_end_request>this.Protocol.GenRequest(this.send_last_rank_data_end);
	}

	public get send_last_rank_data_start_Request(): S2CSproto.send_last_rank_data_start_request {
		return <S2CSproto.send_last_rank_data_start_request>this.Protocol.GenRequest(this.send_last_rank_data_start);
	}

	public get send_rank_data_Request(): S2CSproto.send_rank_data_request {
		return <S2CSproto.send_rank_data_request>this.Protocol.GenRequest(this.send_rank_data);
	}

	public get send_rank_data_end_Request(): S2CSproto.send_rank_data_end_request {
		return <S2CSproto.send_rank_data_end_request>this.Protocol.GenRequest(this.send_rank_data_end);
	}

	public get send_rank_data_start_Request(): S2CSproto.send_rank_data_start_request {
		return <S2CSproto.send_rank_data_start_request>this.Protocol.GenRequest(this.send_rank_data_start);
	}

	public get send_room_act_rank_data_Request(): S2CSproto.send_room_act_rank_data_request {
		return <S2CSproto.send_room_act_rank_data_request>this.Protocol.GenRequest(this.send_room_act_rank_data);
	}

	public get send_room_act_rank_data_end_Request(): S2CSproto.send_room_act_rank_data_end_request {
		return <S2CSproto.send_room_act_rank_data_end_request>this.Protocol.GenRequest(this.send_room_act_rank_data_end);
	}

	public get send_room_act_rank_data_start_Request(): S2CSproto.send_room_act_rank_data_start_request {
		return <S2CSproto.send_room_act_rank_data_start_request>this.Protocol.GenRequest(this.send_room_act_rank_data_start);
	}

	public get skill_remain_time_Request(): S2CSproto.skill_remain_time_request {
		return <S2CSproto.skill_remain_time_request>this.Protocol.GenRequest(this.skill_remain_time);
	}

	public get small_boss_escape_Request(): S2CSproto.small_boss_escape_request {
		return <S2CSproto.small_boss_escape_request>this.Protocol.GenRequest(this.small_boss_escape);
	}

	public get spawn_fish_Request(): S2CSproto.spawn_fish_request {
		return <S2CSproto.spawn_fish_request>this.Protocol.GenRequest(this.spawn_fish);
	}

	public get spawn_fish_array_Request(): S2CSproto.spawn_fish_array_request {
		return <S2CSproto.spawn_fish_array_request>this.Protocol.GenRequest(this.spawn_fish_array);
	}

	public get spawn_small_boss_Request(): S2CSproto.spawn_small_boss_request {
		return <S2CSproto.spawn_small_boss_request>this.Protocol.GenRequest(this.spawn_small_boss);
	}

	public get spec_bullet_score_Request(): S2CSproto.spec_bullet_score_request {
		return <S2CSproto.spec_bullet_score_request>this.Protocol.GenRequest(this.spec_bullet_score);
	}

	public get summon_boss_rewards_Request(): S2CSproto.summon_boss_rewards_request {
		return <S2CSproto.summon_boss_rewards_request>this.Protocol.GenRequest(this.summon_boss_rewards);
	}

	public get switch_cannon_Request(): S2CSproto.switch_cannon_request {
		return <S2CSproto.switch_cannon_request>this.Protocol.GenRequest(this.switch_cannon);
	}

	public get sync_bankruptcy_Request(): S2CSproto.sync_bankruptcy_request {
		return <S2CSproto.sync_bankruptcy_request>this.Protocol.GenRequest(this.sync_bankruptcy);
	}

	public get sync_bomb_fish_click_Request(): S2CSproto.sync_bomb_fish_click_request {
		return <S2CSproto.sync_bomb_fish_click_request>this.Protocol.GenRequest(this.sync_bomb_fish_click);
	}

	public get sync_machine_storm_gold_Request(): S2CSproto.sync_machine_storm_gold_request {
		return <S2CSproto.sync_machine_storm_gold_request>this.Protocol.GenRequest(this.sync_machine_storm_gold);
	}

	public get sync_skill_effect_Request(): S2CSproto.sync_skill_effect_request {
		return <S2CSproto.sync_skill_effect_request>this.Protocol.GenRequest(this.sync_skill_effect);
	}

	public get sync_skill_end_Request(): S2CSproto.sync_skill_end_request {
		return <S2CSproto.sync_skill_end_request>this.Protocol.GenRequest(this.sync_skill_end);
	}

	public get sync_using_cannon_multiple_Request(): S2CSproto.sync_using_cannon_multiple_request {
		return <S2CSproto.sync_using_cannon_multiple_request>this.Protocol.GenRequest(this.sync_using_cannon_multiple);
	}

	public get sync_vip_info_Request(): S2CSproto.sync_vip_info_request {
		return <S2CSproto.sync_vip_info_request>this.Protocol.GenRequest(this.sync_vip_info);
	}

	public get table_clear_fish_Request(): S2CSproto.table_clear_fish_request {
		return <S2CSproto.table_clear_fish_request>this.Protocol.GenRequest(this.table_clear_fish);
	}

	public get table_eat_fish_Request(): S2CSproto.table_eat_fish_request {
		return <S2CSproto.table_eat_fish_request>this.Protocol.GenRequest(this.table_eat_fish);
	}

	public get table_fire_Request(): S2CSproto.table_fire_request {
		return <S2CSproto.table_fire_request>this.Protocol.GenRequest(this.table_fire);
	}

	public get table_fish_net_Request(): S2CSproto.table_fish_net_request {
		return <S2CSproto.table_fish_net_request>this.Protocol.GenRequest(this.table_fish_net);
	}

	public get table_player_sit_down_Request(): S2CSproto.table_player_sit_down_request {
		return <S2CSproto.table_player_sit_down_request>this.Protocol.GenRequest(this.table_player_sit_down);
	}

	public get table_player_stand_up_Request(): S2CSproto.table_player_stand_up_request {
		return <S2CSproto.table_player_stand_up_request>this.Protocol.GenRequest(this.table_player_stand_up);
	}

	public get table_sync_event_Request(): S2CSproto.table_sync_event_request {
		return <S2CSproto.table_sync_event_request>this.Protocol.GenRequest(this.table_sync_event);
	}

	public get user_level_up_Request(): S2CSproto.user_level_up_request {
		return <S2CSproto.user_level_up_request>this.Protocol.GenRequest(this.user_level_up);
	}

}